import type { WorksheetEntry, WorksheetTemplate } from "./types";
import hskVocabulary from "./hsk-vocabulary.json";

type VocabularyRecord = {
  hanzi: string;
  pinyin: string;
  english: string;
};

type TemplateGuidance = Pick<
  WorksheetTemplate,
  "learningGoal" | "teachingTip" | "practiceActivity"
>;

type WorksheetTemplateSeed = Omit<WorksheetTemplate, keyof TemplateGuidance>;

const curatedVocabularyRecords: VocabularyRecord[] = [
  { hanzi: "家庭", pinyin: "jiātíng", english: "family" },
  { hanzi: "妈妈", pinyin: "māma", english: "mother" },
  { hanzi: "爸爸", pinyin: "bàba", english: "father" },
  { hanzi: "哥哥", pinyin: "gēge", english: "older brother" },
  { hanzi: "姐姐", pinyin: "jiějie", english: "older sister" },
  { hanzi: "弟弟", pinyin: "dìdi", english: "younger brother" },
  { hanzi: "妹妹", pinyin: "mèimei", english: "younger sister" },
  { hanzi: "爷爷", pinyin: "yéye", english: "grandfather" },
  { hanzi: "奶奶", pinyin: "nǎinai", english: "grandmother" },
  { hanzi: "外公", pinyin: "wàigōng", english: "maternal grandfather" },
  { hanzi: "外婆", pinyin: "wàipó", english: "maternal grandmother" },
  { hanzi: "儿子", pinyin: "érzi", english: "son" },
  { hanzi: "女儿", pinyin: "nǚ'ér", english: "daughter" },
  { hanzi: "丈夫", pinyin: "zhàngfu", english: "husband" },
  { hanzi: "妻子", pinyin: "qīzi", english: "wife" },
  { hanzi: "叔叔", pinyin: "shūshu", english: "uncle" },
  { hanzi: "阿姨", pinyin: "āyí", english: "aunt" },
  { hanzi: "表哥", pinyin: "biǎogē", english: "older male cousin" },
  { hanzi: "表姐", pinyin: "biǎojiě", english: "older female cousin" },
  { hanzi: "表弟", pinyin: "biǎodì", english: "younger male cousin" },
  { hanzi: "表妹", pinyin: "biǎomèi", english: "younger female cousin" },
  { hanzi: "父母", pinyin: "fùmǔ", english: "parents" },
  { hanzi: "孩子", pinyin: "háizi", english: "child" },
  { hanzi: "亲戚", pinyin: "qīnqi", english: "relative" },
  { hanzi: "一", pinyin: "yī", english: "one" },
  { hanzi: "二", pinyin: "èr", english: "two" },
  { hanzi: "三", pinyin: "sān", english: "three" },
  { hanzi: "四", pinyin: "sì", english: "four" },
  { hanzi: "五", pinyin: "wǔ", english: "five" },
  { hanzi: "六", pinyin: "liù", english: "six" },
  { hanzi: "七", pinyin: "qī", english: "seven" },
  { hanzi: "八", pinyin: "bā", english: "eight" },
  { hanzi: "九", pinyin: "jiǔ", english: "nine" },
  { hanzi: "十", pinyin: "shí", english: "ten" },
  { hanzi: "红色", pinyin: "hóngsè", english: "red" },
  { hanzi: "蓝色", pinyin: "lánsè", english: "blue" },
  { hanzi: "绿色", pinyin: "lǜsè", english: "green" },
  { hanzi: "黄色", pinyin: "huángsè", english: "yellow" },
  { hanzi: "黑色", pinyin: "hēisè", english: "black" },
  { hanzi: "白色", pinyin: "báisè", english: "white" },
  { hanzi: "你好", pinyin: "nǐ hǎo", english: "hello" },
  { hanzi: "早上好", pinyin: "zǎoshang hǎo", english: "good morning" },
  { hanzi: "谢谢", pinyin: "xièxie", english: "thank you" },
  { hanzi: "再见", pinyin: "zàijiàn", english: "goodbye" },
  { hanzi: "请", pinyin: "qǐng", english: "please" },
  { hanzi: "星期一", pinyin: "xīngqīyī", english: "Monday" },
  { hanzi: "星期二", pinyin: "xīngqī'èr", english: "Tuesday" },
  { hanzi: "一月", pinyin: "yīyuè", english: "January" },
  { hanzi: "今天", pinyin: "jīntiān", english: "today" },
  { hanzi: "米饭", pinyin: "mǐfàn", english: "rice" },
  { hanzi: "面条", pinyin: "miàntiáo", english: "noodles" },
  { hanzi: "水", pinyin: "shuǐ", english: "water" },
  { hanzi: "茶", pinyin: "chá", english: "tea" },
  { hanzi: "苹果", pinyin: "píngguǒ", english: "apple" },
  { hanzi: "猫", pinyin: "māo", english: "cat" },
  { hanzi: "狗", pinyin: "gǒu", english: "dog" },
  { hanzi: "熊猫", pinyin: "xióngmāo", english: "panda" },
  { hanzi: "兔子", pinyin: "tùzi", english: "rabbit" },
  { hanzi: "鸟", pinyin: "niǎo", english: "bird" },
  { hanzi: "我", pinyin: "wǒ", english: "I; me" },
  { hanzi: "你", pinyin: "nǐ", english: "you" },
  { hanzi: "他", pinyin: "tā", english: "he; him" },
  { hanzi: "她", pinyin: "tā", english: "she; her" },
  { hanzi: "是", pinyin: "shì", english: "to be" },
  { hanzi: "老师", pinyin: "lǎoshī", english: "teacher" },
  { hanzi: "学生", pinyin: "xuésheng", english: "student" },
  { hanzi: "中国", pinyin: "Zhōngguó", english: "China" },
  { hanzi: "中文", pinyin: "Zhōngwén", english: "Chinese language" },
];

const templateVocabularyRecords: VocabularyRecord[] = [
  { hanzi: "深", pinyin: "shēn", english: "deep; dark" },
  { hanzi: "浅", pinyin: "qiǎn", english: "shallow; light" },
  { hanzi: "您好", pinyin: "nín hǎo", english: "hello (polite)" },
  { hanzi: "星期三", pinyin: "xīngqīsān", english: "Wednesday" },
  { hanzi: "星期四", pinyin: "xīngqīsì", english: "Thursday" },
  { hanzi: "星期五", pinyin: "xīngqīwǔ", english: "Friday" },
  { hanzi: "星期六", pinyin: "xīngqīliù", english: "Saturday" },
  { hanzi: "二月", pinyin: "èryuè", english: "February" },
  { hanzi: "三月", pinyin: "sānyuè", english: "March" },
  { hanzi: "咖啡", pinyin: "kāfēi", english: "coffee" },
  { hanzi: "汤", pinyin: "tāng", english: "soup" },
  { hanzi: "马", pinyin: "mǎ", english: "horse" },
  { hanzi: "牛", pinyin: "niú", english: "cow" },
  { hanzi: "羊", pinyin: "yáng", english: "sheep" },
  { hanzi: "鸭", pinyin: "yā", english: "duck" },
  { hanzi: "老虎", pinyin: "lǎohǔ", english: "tiger" },
  { hanzi: "狮子", pinyin: "shīzi", english: "lion" },
  { hanzi: "猴子", pinyin: "hóuzi", english: "monkey" },
  { hanzi: "大象", pinyin: "dàxiàng", english: "elephant" },
  { hanzi: "洗脸", pinyin: "xǐliǎn", english: "wash one's face" },
  { hanzi: "刷牙", pinyin: "shuāyá", english: "brush one's teeth" },
  { hanzi: "吃早饭", pinyin: "chī zǎofàn", english: "eat breakfast" },
  { hanzi: "吃晚饭", pinyin: "chī wǎnfàn", english: "eat dinner" },
  { hanzi: "看电视", pinyin: "kàn diànshì", english: "watch television" },
  { hanzi: "做作业", pinyin: "zuò zuòyè", english: "do homework" },
  { hanzi: "暖和", pinyin: "nuǎnhuo", english: "warm" },
  { hanzi: "鼻子", pinyin: "bízi", english: "nose" },
  { hanzi: "耳朵", pinyin: "ěrduo", english: "ear" },
  { hanzi: "客厅", pinyin: "kètīng", english: "living room" },
  { hanzi: "卧室", pinyin: "wòshì", english: "bedroom" },
  { hanzi: "厨房", pinyin: "chúfáng", english: "kitchen" },
  { hanzi: "卫生间", pinyin: "wèishēngjiān", english: "bathroom" },
  { hanzi: "窗户", pinyin: "chuānghu", english: "window" },
  { hanzi: "冰箱", pinyin: "bīngxiāng", english: "refrigerator" },
  { hanzi: "沙发", pinyin: "shāfā", english: "sofa" },
  { hanzi: "火车站", pinyin: "huǒchēzhàn", english: "train station" },
  { hanzi: "行李", pinyin: "xíngli", english: "luggage" },
  { hanzi: "到达", pinyin: "dàodá", english: "arrive" },
  { hanzi: "城市", pinyin: "chéngshì", english: "city" },
  { hanzi: "裤子", pinyin: "kùzi", english: "trousers" },
  { hanzi: "现金", pinyin: "xiànjīn", english: "cash" },
  { hanzi: "点菜", pinyin: "diǎncài", english: "order dishes" },
  { hanzi: "服务员", pinyin: "fúwùyuán", english: "server" },
  { hanzi: "盘子", pinyin: "pánzi", english: "plate" },
  { hanzi: "结账", pinyin: "jiézhàng", english: "pay the bill" },
  { hanzi: "跑步", pinyin: "pǎobù", english: "run" },
  { hanzi: "游泳", pinyin: "yóuyǒng", english: "swim" },
  { hanzi: "足球", pinyin: "zúqiú", english: "football" },
  { hanzi: "羽毛球", pinyin: "yǔmáoqiú", english: "badminton" },
  { hanzi: "跳舞", pinyin: "tiàowǔ", english: "dance" },
  { hanzi: "画画", pinyin: "huàhuà", english: "draw pictures" },
  { hanzi: "拍照", pinyin: "pāizhào", english: "take a photo" },
  { hanzi: "红包", pinyin: "hóngbāo", english: "red envelope" },
  { hanzi: "灯笼", pinyin: "dēnglong", english: "lantern" },
  { hanzi: "年糕", pinyin: "niángāo", english: "New Year rice cake" },
  { hanzi: "团圆", pinyin: "tuányuán", english: "family reunion" },
  { hanzi: "拜年", pinyin: "bàinián", english: "give New Year greetings" },
  { hanzi: "烟花", pinyin: "yānhuā", english: "fireworks" },
  { hanzi: "龙", pinyin: "lóng", english: "dragon" },
  { hanzi: "舞狮", pinyin: "wǔshī", english: "lion dance" },
  { hanzi: "祝福", pinyin: "zhùfú", english: "good wishes" },
  { hanzi: "传统", pinyin: "chuántǒng", english: "tradition" },
  { hanzi: "老板", pinyin: "lǎobǎn", english: "boss" },
  { hanzi: "护士", pinyin: "hùshi", english: "nurse" },
  { hanzi: "工程师", pinyin: "gōngchéngshī", english: "engineer" },
  { hanzi: "职业", pinyin: "zhíyè", english: "occupation" },
];

const p0TemplateVocabularyRecords: VocabularyRecord[] = [
  { hanzi: "\u6a2a", pinyin: "heng", english: "horizontal stroke" },
  { hanzi: "\u7ad6", pinyin: "shu", english: "vertical stroke" },
  { hanzi: "\u6487", pinyin: "pie", english: "left-falling stroke" },
  { hanzi: "\u637a", pinyin: "na", english: "right-falling stroke" },
  { hanzi: "\u70b9", pinyin: "dian", english: "dot stroke" },
  { hanzi: "\u63d0", pinyin: "ti", english: "rising stroke" },
  { hanzi: "\u6298", pinyin: "zhe", english: "turning stroke" },
  { hanzi: "\u94a9", pinyin: "gou", english: "hook stroke" },
  { hanzi: "\u5f2f", pinyin: "wan", english: "curved stroke" },
  { hanzi: "\u659c\u94a9", pinyin: "xie gou", english: "slanting hook" },
  { hanzi: "\u7ad6\u94a9", pinyin: "shu gou", english: "vertical hook" },
  { hanzi: "\u6a2a\u6298", pinyin: "heng zhe", english: "horizontal turn" },
  { hanzi: "\u6a2a\u6487", pinyin: "heng pie", english: "horizontal left-falling stroke" },
  { hanzi: "\u70b9\u63d0", pinyin: "dian ti", english: "dot and rising stroke" },
  { hanzi: "\u7ad6\u5f2f\u94a9", pinyin: "shu wan gou", english: "vertical bend hook" },
  { hanzi: "\u5367\u94a9", pinyin: "wo gou", english: "lying hook" },
  { hanzi: "\u4ebb", pinyin: "ren", english: "person radical" },
  { hanzi: "\u6c35", pinyin: "shui", english: "water radical" },
  { hanzi: "\u624c", pinyin: "shou", english: "hand radical" },
  { hanzi: "\u8279", pinyin: "cao", english: "grass radical" },
  { hanzi: "\u5fc4", pinyin: "xin", english: "heart radical" },
  { hanzi: "\u8ba0", pinyin: "yan", english: "speech radical" },
  { hanzi: "\u5b80", pinyin: "mian", english: "roof radical" },
  { hanzi: "\u8fb6", pinyin: "chuo", english: "walk radical" },
  { hanzi: "\u9485", pinyin: "jin", english: "metal radical" },
  { hanzi: "\u7e9f", pinyin: "si", english: "silk radical" },
  { hanzi: "\u9963", pinyin: "shi", english: "food radical" },
  { hanzi: "\u72ad", pinyin: "quan", english: "dog radical" },
  { hanzi: "\u7592", pinyin: "bing", english: "sickness radical" },
  { hanzi: "\u8864", pinyin: "yi", english: "clothing radical" },
  { hanzi: "\u793b", pinyin: "shi", english: "spirit radical" },
  { hanzi: "\u961d", pinyin: "fu", english: "mound radical" },
  { hanzi: "\u6535", pinyin: "pu", english: "tap radical" },
  { hanzi: "\u5202", pinyin: "dao", english: "knife radical" },
  { hanzi: "\u51ab", pinyin: "bing", english: "ice radical" },
  { hanzi: "\u56d7", pinyin: "wei", english: "enclosure radical" },
  { hanzi: "\u6728", pinyin: "mu", english: "wood" },
  { hanzi: "\u706b", pinyin: "huo", english: "fire" },
  { hanzi: "\u7530", pinyin: "tian", english: "field" },
  { hanzi: "\u6625\u7720\u4e0d\u89c9\u6653", pinyin: "chun mian bu jue xiao", english: "spring sleep, unaware of dawn" },
  { hanzi: "\u5904\u5904\u95fb\u557c\u9e1f", pinyin: "chu chu wen ti niao", english: "birdsong is heard everywhere" },
  { hanzi: "\u591c\u6765\u98ce\u96e8\u58f0", pinyin: "ye lai feng yu sheng", english: "wind and rain sounded at night" },
  { hanzi: "\u82b1\u843d\u77e5\u591a\u5c11", pinyin: "hua luo zhi duo shao", english: "who knows how many flowers fell" },
  { hanzi: "\u5e8a\u524d\u660e\u6708\u5149", pinyin: "chuang qian ming yue guang", english: "bright moonlight before the bed" },
  { hanzi: "\u7591\u662f\u5730\u4e0a\u971c", pinyin: "yi shi di shang shuang", english: "it seems like frost on the ground" },
  { hanzi: "\u4e3e\u5934\u671b\u660e\u6708", pinyin: "ju tou wang ming yue", english: "raise the head and gaze at the moon" },
  { hanzi: "\u4f4e\u5934\u601d\u6545\u4e61", pinyin: "di tou si gu xiang", english: "lower the head and think of home" },
  { hanzi: "\u767d\u65e5\u4f9d\u5c71\u5c3d", pinyin: "bai ri yi shan jin", english: "the white sun sets beyond the hills" },
  { hanzi: "\u9ec4\u6cb3\u5165\u6d77\u6d41", pinyin: "huang he ru hai liu", english: "the Yellow River flows into the sea" },
  { hanzi: "\u6b32\u7a77\u5343\u91cc\u76ee", pinyin: "yu qiong qian li mu", english: "to see a thousand li farther" },
  { hanzi: "\u66f4\u4e0a\u4e00\u5c42\u697c", pinyin: "geng shang yi ceng lou", english: "climb one more storey" },
  { hanzi: "\u9504\u79be\u65e5\u5f53\u5348", pinyin: "chu he ri dang wu", english: "hoe grain under the noon sun" },
  { hanzi: "\u6c57\u6ef4\u79be\u4e0b\u571f", pinyin: "han di he xia tu", english: "sweat drops into the soil" },
  { hanzi: "\u8c01\u77e5\u76d8\u4e2d\u9910", pinyin: "shui zhi pan zhong can", english: "who knows the food in the bowl" },
  { hanzi: "\u7c92\u7c92\u7686\u8f9b\u82e6", pinyin: "li li jie xin ku", english: "every grain comes from hard work" },
];

const mvpTemplateVocabularyRecords: VocabularyRecord[] = [
  { hanzi: "\u65f6", pinyin: "shi", english: "time" },
  { hanzi: "\u4ee5", pinyin: "yi", english: "with; by" },
  { hanzi: "\u81ea", pinyin: "zi", english: "self" },
  { hanzi: "\u4e4b", pinyin: "zhi", english: "of" },
  { hanzi: "\u53ef", pinyin: "ke", english: "can; may" },
  { hanzi: "\u4e48", pinyin: "me", english: "question suffix" },
  { hanzi: "\u5fc3", pinyin: "xin", english: "heart" },
  { hanzi: "\u800c", pinyin: "er", english: "and; but" },
  { hanzi: "\u7136", pinyin: "ran", english: "so; thus" },
  { hanzi: "\u4e8e", pinyin: "yu", english: "at; in" },
  { hanzi: "\u4f5c", pinyin: "zuo", english: "to do" },
  { hanzi: "\u6587", pinyin: "wen", english: "language; writing" },
  { hanzi: "\u65e0", pinyin: "wu", english: "without" },
  { hanzi: "\u4e3b", pinyin: "zhu", english: "main" },
  { hanzi: "\u65b9", pinyin: "fang", english: "direction" },
  { hanzi: "\u5982", pinyin: "ru", english: "as; like" },
  { hanzi: "\u6240", pinyin: "suo", english: "place; that which" },
  { hanzi: "\u7ecf", pinyin: "jing", english: "classic; pass through" },
  { hanzi: "\u516c", pinyin: "gong", english: "public" },
  { hanzi: "\u540c", pinyin: "tong", english: "same" },
  { hanzi: "\u5df2", pinyin: "yi", english: "already" },
  { hanzi: "\u77e5", pinyin: "zhi", english: "to know" },
];

const p0ExpansionVocabularyRecords: VocabularyRecord[] = [
  { hanzi: "\u6c11", pinyin: "min", english: "people" },
  { hanzi: "\u6837", pinyin: "yang", english: "sample; appearance" },
  { hanzi: "\u73b0", pinyin: "xian", english: "now; appear" },
  { hanzi: "\u5c06", pinyin: "jiang", english: "will; to take" },
  { hanzi: "\u8eab", pinyin: "shen", english: "body" },
  { hanzi: "\u4e9b", pinyin: "xie", english: "some" },
  { hanzi: "\u4e0e", pinyin: "yu", english: "and; with" },
  { hanzi: "\u610f", pinyin: "yi", english: "meaning; idea" },
  { hanzi: "\u628a", pinyin: "ba", english: "handle; to hold" },
  { hanzi: "\u6cd5", pinyin: "fa", english: "method; law" },
  { hanzi: "\u6b64", pinyin: "ci", english: "this" },
  { hanzi: "\u5b9e", pinyin: "shi", english: "real; solid" },
  { hanzi: "\u7406", pinyin: "li", english: "reason; manage" },
  { hanzi: "\u7f8e", pinyin: "mei", english: "beautiful" },
  { hanzi: "\u660e", pinyin: "ming", english: "bright; clear" },
  { hanzi: "\u5176", pinyin: "qi", english: "its; their" },
  { hanzi: "\u79cd", pinyin: "zhong", english: "kind; type" },
  { hanzi: "\u58f0", pinyin: "sheng", english: "sound; voice" },
  { hanzi: "\u5de5", pinyin: "gong", english: "work" },
  { hanzi: "\u5df1", pinyin: "ji", english: "self" },
  { hanzi: "\u513f", pinyin: "er", english: "child" },
  { hanzi: "\u8005", pinyin: "zhe", english: "person; one who" },
  { hanzi: "\u60c5", pinyin: "qing", english: "feeling; situation" },
  { hanzi: "\u90e8", pinyin: "bu", english: "part; department" },
  { hanzi: "\u5b9a", pinyin: "ding", english: "fixed; decide" },
  { hanzi: "\u529b", pinyin: "li", english: "strength" },
  { hanzi: "\u673a", pinyin: "ji", english: "machine; opportunity" },
  { hanzi: "\u4e1a", pinyin: "ye", english: "business; study" },
  { hanzi: "\u4ec0", pinyin: "shen", english: "what" },
  { hanzi: "\u4fbf", pinyin: "bian", english: "convenient" },
  { hanzi: "\u56e0", pinyin: "yin", english: "because; cause" },
  { hanzi: "\u88ab", pinyin: "bei", english: "passive marker; quilt" },
  { hanzi: "\u76f8", pinyin: "xiang", english: "mutual; appearance" },
  { hanzi: "\u653f", pinyin: "zheng", english: "government" },
  { hanzi: "\u4e16", pinyin: "shi", english: "world; generation" },
  { hanzi: "\u5e76", pinyin: "bing", english: "also; together" },
  { hanzi: "\u5185", pinyin: "nei", english: "inside" },
  { hanzi: "\u5316", pinyin: "hua", english: "change; transform" },
  { hanzi: "\u7531", pinyin: "you", english: "from; reason" },
  { hanzi: "\u5374", pinyin: "que", english: "but; yet" },
  { hanzi: "\u4ee3", pinyin: "dai", english: "generation; replace" },
  { hanzi: "\u519b", pinyin: "jun", english: "army" },
  { hanzi: "\u4ea7", pinyin: "chan", english: "produce; property" },
  { hanzi: "\u5165", pinyin: "ru", english: "enter" },
  { hanzi: "\u4f53", pinyin: "ti", english: "body; form" },
  { hanzi: "\u793e\u4f1a", pinyin: "she hui", english: "society" },
  { hanzi: "\u6587\u5316", pinyin: "wen hua", english: "culture" },
  { hanzi: "\u7ecf\u6d4e", pinyin: "jing ji", english: "economy" },
  { hanzi: "\u73af\u5883", pinyin: "huan jing", english: "environment" },
  { hanzi: "\u6559\u80b2", pinyin: "jiao yu", english: "education" },
  { hanzi: "\u79d1\u6280", pinyin: "ke ji", english: "technology" },
  { hanzi: "\u653f\u5e9c", pinyin: "zheng fu", english: "government" },
  { hanzi: "\u5386\u53f2", pinyin: "li shi", english: "history" },
  { hanzi: "\u53d1\u5c55", pinyin: "fa zhan", english: "to develop" },
  { hanzi: "\u5f71\u54cd", pinyin: "ying xiang", english: "influence" },
  { hanzi: "\u7ecf\u9a8c", pinyin: "jing yan", english: "experience" },
  { hanzi: "\u673a\u4f1a", pinyin: "ji hui", english: "opportunity" },
  { hanzi: "\u91cd\u8981", pinyin: "zhong yao", english: "important" },
  { hanzi: "\u89e3\u51b3", pinyin: "jie jue", english: "to solve" },
  { hanzi: "\u9009\u62e9", pinyin: "xuan ze", english: "to choose" },
  { hanzi: "\u4fdd\u62a4", pinyin: "bao hu", english: "to protect" },
  { hanzi: "\u8d23\u4efb", pinyin: "ze ren", english: "responsibility" },
  { hanzi: "\u89c2\u70b9", pinyin: "guan dian", english: "viewpoint" },
  { hanzi: "\u6761\u4ef6", pinyin: "tiao jian", english: "condition" },
  { hanzi: "\u63d0\u9ad8", pinyin: "ti gao", english: "to improve" },
  { hanzi: "\u7ba1\u7406", pinyin: "guan li", english: "to manage" },
  { hanzi: "\u7814\u7a76", pinyin: "yan jiu", english: "research" },
  { hanzi: "\u6539\u53d8", pinyin: "gai bian", english: "to change" },
  { hanzi: "\u8054\u7cfb", pinyin: "lian xi", english: "contact; connection" },
  { hanzi: "\u56fd\u9645", pinyin: "guo ji", english: "international" },
  { hanzi: "\u4f20\u7edf", pinyin: "chuan tong", english: "tradition" },
  { hanzi: "\u73b0\u4ee3", pinyin: "xian dai", english: "modern" },
  { hanzi: "\u8d44\u6e90", pinyin: "zi yuan", english: "resource" },
  { hanzi: "\u538b\u529b", pinyin: "ya li", english: "pressure" },
  { hanzi: "\u91c7\u53d6", pinyin: "cai qu", english: "to adopt" },
  { hanzi: "\u7279\u70b9", pinyin: "te dian", english: "feature" },
  { hanzi: "\u5efa\u8bae", pinyin: "jian yi", english: "suggestion" },
  { hanzi: "\u53cd\u5bf9", pinyin: "fan dui", english: "to oppose" },
  { hanzi: "\u652f\u6301", pinyin: "zhi chi", english: "to support" },
  { hanzi: "\u4fdd\u6301", pinyin: "bao chi", english: "to keep" },
  { hanzi: "\u7ed3\u679c", pinyin: "jie guo", english: "result" },
  { hanzi: "\u539f\u56e0", pinyin: "yuan yin", english: "reason" },
  { hanzi: "\u8fc7\u7a0b", pinyin: "guo cheng", english: "process" },
  { hanzi: "\u6807\u51c6", pinyin: "biao zhun", english: "standard" },
  { hanzi: "\u80fd\u529b", pinyin: "neng li", english: "ability" },
  { hanzi: "\u54c1\u724c", pinyin: "pin pai", english: "brand" },
  { hanzi: "\u5e02\u573a", pinyin: "shi chang", english: "market" },
  { hanzi: "\u6d88\u8d39", pinyin: "xiao fei", english: "to consume" },
  { hanzi: "\u670d\u52a1", pinyin: "fu wu", english: "service" },
  { hanzi: "\u8d28\u91cf", pinyin: "zhi liang", english: "quality" },
  { hanzi: "\u9879\u76ee", pinyin: "xiang mu", english: "project" },
  { hanzi: "\u60c5\u51b5", pinyin: "qing kuang", english: "situation" },
  { hanzi: "\u6570\u636e", pinyin: "shu ju", english: "data" },
  { hanzi: "\u8d8b\u52bf", pinyin: "qu shi", english: "trend" },
  { hanzi: "\u5408\u4f5c", pinyin: "he zuo", english: "cooperation" },
  { hanzi: "\u7b2c", pinyin: "di", english: "ordinal prefix" },
  { hanzi: "\u4e24", pinyin: "liang", english: "two" },
  { hanzi: "\u4e8c\u5341", pinyin: "er shi", english: "twenty" },
  { hanzi: "\u4e09\u5341", pinyin: "san shi", english: "thirty" },
  { hanzi: "\u56db\u5341", pinyin: "si shi", english: "forty" },
  { hanzi: "\u4e94\u5341", pinyin: "wu shi", english: "fifty" },
  { hanzi: "\u516d\u5341", pinyin: "liu shi", english: "sixty" },
  { hanzi: "\u4e03\u5341", pinyin: "qi shi", english: "seventy" },
  { hanzi: "\u516b\u5341", pinyin: "ba shi", english: "eighty" },
  { hanzi: "\u4e5d\u5341", pinyin: "jiu shi", english: "ninety" },
  { hanzi: "\u4e00\u767e", pinyin: "yi bai", english: "one hundred" },
  { hanzi: "\u4e00\u4e2a", pinyin: "yi ge", english: "one item" },
  { hanzi: "\u4e24\u4e2a", pinyin: "liang ge", english: "two items" },
  { hanzi: "\u4e09\u672c", pinyin: "san ben", english: "three volumes" },
  { hanzi: "\u56db\u5f20", pinyin: "si zhang", english: "four flat objects" },
  { hanzi: "\u4e94\u53ea", pinyin: "wu zhi", english: "five animals or one of a pair" },
  { hanzi: "\u516d\u6761", pinyin: "liu tiao", english: "six long thin things" },
  { hanzi: "\u4e03\u4ef6", pinyin: "qi jian", english: "seven matters or clothes" },
  { hanzi: "\u516b\u676f", pinyin: "ba bei", english: "eight cups" },
  { hanzi: "\u4e5d\u53cc", pinyin: "jiu shuang", english: "nine pairs" },
  { hanzi: "\u5341\u53e3", pinyin: "shi kou", english: "ten family members" },
  { hanzi: "\u4f4d", pinyin: "wei", english: "polite measure word for people" },
  { hanzi: "\u540d", pinyin: "ming", english: "measure word for people" },
  { hanzi: "\u672c", pinyin: "ben", english: "measure word for books" },
  { hanzi: "\u5f20", pinyin: "zhang", english: "measure word for flat objects" },
  { hanzi: "\u53ea", pinyin: "zhi", english: "measure word for animals or one of a pair" },
  { hanzi: "\u6761", pinyin: "tiao", english: "measure word for long thin things" },
  { hanzi: "\u4ef6", pinyin: "jian", english: "measure word for clothes or matters" },
  { hanzi: "\u676f", pinyin: "bei", english: "cup; measure word for cups" },
  { hanzi: "\u53cc", pinyin: "shuang", english: "pair" },
  { hanzi: "\u53e3", pinyin: "kou", english: "mouth; family member measure word" },
  { hanzi: "\u5bb6", pinyin: "jia", english: "family; measure word for businesses" },
  { hanzi: "\u8f86", pinyin: "liang", english: "measure word for vehicles" },
  { hanzi: "\u6240", pinyin: "suo", english: "measure word for schools or houses" },
  { hanzi: "\u5ea7", pinyin: "zuo", english: "measure word for buildings or mountains" },
  { hanzi: "\u5757", pinyin: "kuai", english: "piece; yuan" },
  { hanzi: "\u6b21", pinyin: "ci", english: "time; occurrence" },
  { hanzi: "\u505a", pinyin: "zuo", english: "to do; to make" },
  { hanzi: "\u770b", pinyin: "kan", english: "to see; to watch" },
  { hanzi: "\u542c", pinyin: "ting", english: "to listen" },
  { hanzi: "\u8bf4", pinyin: "shuo", english: "to speak" },
  { hanzi: "\u5199", pinyin: "xie", english: "to write" },
  { hanzi: "\u8bfb", pinyin: "du", english: "to read" },
  { hanzi: "\u95ee", pinyin: "wen", english: "to ask" },
  { hanzi: "\u56de\u7b54", pinyin: "hui da", english: "to answer" },
  { hanzi: "\u5b66", pinyin: "xue", english: "to study" },
  { hanzi: "\u6559", pinyin: "jiao", english: "to teach" },
  { hanzi: "\u4e70", pinyin: "mai", english: "to buy" },
  { hanzi: "\u5356", pinyin: "mai", english: "to sell" },
  { hanzi: "\u5f00", pinyin: "kai", english: "to open" },
  { hanzi: "\u5173", pinyin: "guan", english: "to close" },
  { hanzi: "\u6765", pinyin: "lai", english: "to come" },
  { hanzi: "\u53bb", pinyin: "qu", english: "to go" },
  { hanzi: "\u8d70", pinyin: "zou", english: "to walk" },
  { hanzi: "\u8dd1", pinyin: "pao", english: "to run" },
  { hanzi: "\u5403", pinyin: "chi", english: "to eat" },
  { hanzi: "\u559d", pinyin: "he", english: "to drink" },
  { hanzi: "\u7ed9", pinyin: "gei", english: "to give" },
  { hanzi: "\u627e", pinyin: "zhao", english: "to look for" },
  { hanzi: "\u7528", pinyin: "yong", english: "to use" },
  { hanzi: "\u60f3", pinyin: "xiang", english: "to think; to want" },
  { hanzi: "\u559c\u6b22", pinyin: "xi huan", english: "to like" },
  { hanzi: "\u5e2e", pinyin: "bang", english: "to help" },
  { hanzi: "\u7b49", pinyin: "deng", english: "to wait" },
  { hanzi: "\u5b8c", pinyin: "wan", english: "to finish" },
  { hanzi: "\u8fdb", pinyin: "jin", english: "to enter" },
  { hanzi: "\u51fa", pinyin: "chu", english: "to exit" },
  { hanzi: "\u8d77", pinyin: "qi", english: "to rise" },
  { hanzi: "\u4f4f", pinyin: "zhu", english: "to live" },
  { hanzi: "\u5750", pinyin: "zuo", english: "to sit; to ride" },
  { hanzi: "\u7ad9", pinyin: "zhan", english: "to stand" },
  { hanzi: "\u7b11", pinyin: "xiao", english: "to smile" },
  { hanzi: "\u54ed", pinyin: "ku", english: "to cry" },
  { hanzi: "\u89c9\u5f97", pinyin: "jue de", english: "to feel; to think" },
  { hanzi: "\u77e5\u9053", pinyin: "zhi dao", english: "to know" },
  { hanzi: "\u660e\u767d", pinyin: "ming bai", english: "to understand" },
  { hanzi: "\u51b3\u5b9a", pinyin: "jue ding", english: "to decide" },
  { hanzi: "\u5e0c\u671b", pinyin: "xi wang", english: "to hope" },
  { hanzi: "\u53ef\u4ee5", pinyin: "ke yi", english: "can; may" },
  { hanzi: "\u5e94\u8be5", pinyin: "ying gai", english: "should" },
  { hanzi: "\u53d1\u73b0", pinyin: "fa xian", english: "to discover" },
  { hanzi: "\u53c2\u52a0", pinyin: "can jia", english: "to participate" },
  { hanzi: "\u7ec3\u4e60", pinyin: "lian xi", english: "to practise" },
];

const top100ChineseCharacterWords = [
  "\u7684", "\u4e00", "\u662f", "\u4e0d", "\u4e86", "\u5728", "\u4eba", "\u6709", "\u6211", "\u4ed6",
  "\u8fd9", "\u4e2d", "\u5927", "\u6765", "\u4e0a", "\u56fd", "\u4e2a", "\u5230", "\u8bf4", "\u4eec",
  "\u4e3a", "\u5b50", "\u548c", "\u4f60", "\u5730", "\u51fa", "\u9053", "\u4e5f", "\u65f6", "\u5e74",
  "\u5f97", "\u5c31", "\u90a3", "\u8981", "\u4e0b", "\u4ee5", "\u751f", "\u4f1a", "\u81ea", "\u7740",
  "\u53bb", "\u4e4b", "\u8fc7", "\u5bb6", "\u5b66", "\u5bf9", "\u53ef", "\u5979", "\u91cc", "\u540e",
  "\u5c0f", "\u4e48", "\u5fc3", "\u591a", "\u5929", "\u800c", "\u80fd", "\u597d", "\u90fd", "\u7136",
  "\u6ca1", "\u65e5", "\u4e8e", "\u8d77", "\u8fd8", "\u53d1", "\u6210", "\u4e8b", "\u53ea", "\u4f5c",
  "\u5f53", "\u60f3", "\u770b", "\u6587", "\u65e0", "\u5f00", "\u624b", "\u5341", "\u7528", "\u4e3b",
  "\u884c", "\u65b9", "\u53c8", "\u5982", "\u524d", "\u6240", "\u672c", "\u89c1", "\u7ecf", "\u5934",
  "\u9762", "\u516c", "\u540c", "\u4e09", "\u5df2", "\u8001", "\u4ece", "\u52a8", "\u4e24", "\u957f",
];

const top200AdditionalChineseCharacterWords = [
  "\u77e5", "\u6c11", "\u6837", "\u73b0", "\u5206", "\u5c06", "\u5916", "\u4f46", "\u8eab", "\u4e9b",
  "\u4e0e", "\u9ad8", "\u610f", "\u628a", "\u6cd5", "\u6b64", "\u5b9e", "\u56de", "\u4e8c", "\u7406",
  "\u7f8e", "\u70b9", "\u6708", "\u660e", "\u5176", "\u79cd", "\u58f0", "\u5168", "\u5de5", "\u5df1",
  "\u8bdd", "\u513f", "\u8005", "\u5411", "\u60c5", "\u90e8", "\u6b63", "\u540d", "\u5b9a", "\u5973",
  "\u95ee", "\u529b", "\u673a", "\u7ed9", "\u7b49", "\u51e0", "\u5f88", "\u4e1a", "\u6700", "\u95f4",
  "\u65b0", "\u4ec0", "\u6253", "\u4fbf", "\u4f4d", "\u56e0", "\u91cd", "\u88ab", "\u8d70", "\u7535",
  "\u56db", "\u7b2c", "\u95e8", "\u76f8", "\u6b21", "\u4e1c", "\u653f", "\u6d77", "\u53e3", "\u6559",
  "\u897f", "\u518d", "\u5e73", "\u771f", "\u542c", "\u4e16", "\u6c14", "\u4fe1", "\u5317", "\u5c11",
  "\u5173", "\u5e76", "\u5185", "\u52a0", "\u5316", "\u7531", "\u5374", "\u4ee3", "\u519b", "\u4ea7",
  "\u5165", "\u5148", "\u5c71", "\u4e94", "\u592a", "\u6c34", "\u4e07", "\u5e02", "\u773c", "\u4f53",
];

const top200ChineseCharacterWords = [
  ...top100ChineseCharacterWords,
  ...top200AdditionalChineseCharacterWords,
];

const vocabularyRecords: VocabularyRecord[] = Array.from(
  new Map(
    [
      ...(hskVocabulary as VocabularyRecord[]),
      ...curatedVocabularyRecords,
      ...templateVocabularyRecords,
      ...p0TemplateVocabularyRecords,
      ...mvpTemplateVocabularyRecords,
      ...p0ExpansionVocabularyRecords,
    ].map(
      (record) => [record.hanzi, record],
    ),
  ).values(),
);

export const localVocabularySize = vocabularyRecords.length;

export const vocabularyByEnglish = new Map(
  vocabularyRecords.map((record) => [record.english.toLowerCase(), record]),
);

export const vocabularyByHanzi = new Map(
  vocabularyRecords.map((record) => [record.hanzi, record]),
);

function entriesFor(words: string[]): WorksheetEntry[] {
  return words.map((word, index) => {
    const record =
      vocabularyByHanzi.get(word) ?? vocabularyByEnglish.get(word.toLowerCase());

    return {
      id: `row-${index + 1}`,
      hanzi: record?.hanzi ?? word,
      pinyin: record?.pinyin ?? "",
      english: record?.english ?? "",
      status: record ? "complete" : "needs-review",
    };
  });
}

const familyWords = curatedVocabularyRecords
  .slice(0, 24)
  .map((item) => item.hanzi);

const baseWorksheetTemplates: WorksheetTemplateSeed[] = [
  {
    slug: "family",
    recommendedProfile: "kids",
    title: "Family",
    chineseTitle: "我的家人",
    description: "Practise words for parents, siblings, grandparents, and other close family members.",
    age: "Ages 4–8",
    level: "Beginner",
    wordCount: 24,
    category: "kids",
    entries: entriesFor(familyWords),
  },
  {
    slug: "numbers",
    recommendedProfile: "kids",
    title: "Numbers",
    chineseTitle: "数字",
    description: "Practise zero to ten, larger number units, and the Chinese word for number.",
    age: "Ages 4–8",
    level: "Beginner",
    wordCount: 20,
    category: "kids",
    entries: entriesFor(["一", "二", "三", "四", "五", "六", "七", "八", "九", "十"]),
  },
  {
    slug: "colors",
    recommendedProfile: "kids",
    title: "Colors",
    chineseTitle: "颜色",
    description: "Practise basic colour names, short forms such as 红 and 蓝, and words for light and dark shades.",
    age: "Ages 4–8",
    level: "Beginner",
    wordCount: 16,
    category: "topics",
    entries: entriesFor(["红色", "蓝色", "绿色", "黄色", "黑色", "白色"]),
  },
  {
    slug: "greetings",
    recommendedProfile: "adult",
    title: "Greetings",
    chineseTitle: "问候语",
    description: "Practise greetings, thanks, apologies, polite questions, and phrases for meeting someone.",
    age: "All ages",
    level: "Beginner",
    wordCount: 18,
    category: "topics",
    entries: entriesFor(["你好", "早上好", "谢谢", "再见", "请"]),
  },
  {
    slug: "days-months",
    recommendedProfile: "kids",
    title: "Days & Months",
    chineseTitle: "星期与月份",
    description: "Practise weekdays, early months, and time words such as today, tomorrow, and weekend.",
    age: "Ages 6+",
    level: "Elementary",
    wordCount: 20,
    category: "topics",
    entries: entriesFor(["星期一", "星期二", "一月", "今天"]),
  },
  {
    slug: "food-drinks",
    recommendedProfile: "kids",
    title: "Food & Drinks",
    chineseTitle: "食物与饮品",
    description: "Practise words for staple foods, drinks, fruit, and the three main meals of the day.",
    age: "Ages 6–10",
    level: "Elementary",
    wordCount: 28,
    category: "topics",
    entries: entriesFor(["米饭", "面条", "水", "茶", "苹果"]),
  },
  {
    slug: "animals-kids",
    recommendedProfile: "kids",
    title: "Animals for Kids",
    chineseTitle: "动物",
    description: "Practise familiar pets, farm animals, birds, and zoo animals with younger learners.",
    age: "Ages 4–8",
    level: "Beginner",
    wordCount: 24,
    category: "kids",
    entries: entriesFor(["猫", "狗", "熊猫", "兔子", "鸟"]),
  },
  {
    slug: "hsk-1",
    recommendedProfile: "adult",
    title: "HSK 1 Writing Practice",
    chineseTitle: "HSK 一级",
    description: "Practise a starter group of HSK 1 pronouns, verbs, people, places, and classroom words.",
    age: "Teens & Adults",
    level: "HSK 1",
    wordCount: 150,
    category: "hsk",
    entries: entriesFor(["我", "你", "他", "她", "是", "老师", "学生", "中国", "中文"]),
  },
];

const expandedTemplateWords: Record<string, string[]> = {
  numbers: ["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "百", "千", "万", "数字"],
  colors: ["红色", "蓝色", "绿色", "黄色", "黑色", "白色", "颜色", "红", "蓝", "绿", "黄", "黑", "白", "深", "浅"],
  greetings: ["你好", "早上好", "谢谢", "再见", "请", "不客气", "对不起", "没关系", "欢迎", "晚安", "您好", "早", "请问", "认识", "见面"],
  "days-months": ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日", "一月", "二月", "三月", "今天", "明天", "昨天", "日期", "周末"],
  "food-drinks": ["米饭", "面条", "水", "茶", "苹果", "菜", "水果", "鸡蛋", "牛奶", "咖啡", "面包", "肉", "鱼", "饺子", "汤", "早饭", "午饭", "晚饭"],
  "animals-kids": ["猫", "狗", "熊猫", "兔子", "鸟", "鱼", "马", "牛", "羊", "鸡", "鸭", "老虎", "狮子", "猴子", "大象"],
  "hsk-1": ["我", "你", "他", "她", "是", "有", "在", "好", "不", "人", "老师", "学生", "学校", "中国", "中文", "学习", "写", "读", "说", "听"],
};

type TemplateDraft = Omit<WorksheetTemplateSeed, "entries" | "wordCount"> & {
  words: string[];
};

const additionalTemplateDrafts: TemplateDraft[] = [
  {
    slug: "school-classroom",
    recommendedProfile: "kids",
    title: "School & Classroom",
    chineseTitle: "学校与教室",
    description: "Practise the people, objects, instructions, and tasks students meet in a Chinese classroom.",
    age: "Ages 6+",
    level: "Beginner",
    category: "kids",
    words: ["老师", "学生", "学校", "教室", "书", "本子", "笔", "桌子", "椅子", "学习", "写", "读", "说", "听", "问题", "回答", "作业", "考试"],
  },
  {
    slug: "daily-routine",
    recommendedProfile: "adult",
    title: "Daily Routine",
    chineseTitle: "日常生活",
    description: "Practise words for getting up, going to school, eating, and going to bed.",
    age: "Ages 8+",
    level: "Elementary",
    category: "topics",
    words: ["起床", "洗脸", "刷牙", "吃早饭", "上班", "上学", "下班", "回家", "吃晚饭", "睡觉", "休息", "洗澡", "看电视", "读书", "学习", "做作业"],
  },
  {
    slug: "weather-seasons",
    recommendedProfile: "kids",
    title: "Weather & Seasons",
    chineseTitle: "天气与季节",
    description: "Practise weather conditions, temperature words, and the names of all four seasons.",
    age: "Ages 6+",
    level: "Elementary",
    category: "topics",
    words: ["天气", "晴", "阴", "多云", "下雨", "下雪", "风", "热", "冷", "暖和", "凉快", "春天", "夏天", "秋天", "冬天", "温度"],
  },
  {
    slug: "body-health",
    recommendedProfile: "adult",
    title: "Body & Health",
    chineseTitle: "身体与健康",
    description: "Practise body parts, common health words, and vocabulary for doctors, hospitals, and rest.",
    age: "Ages 8+",
    level: "Elementary",
    category: "topics",
    words: ["头", "脸", "眼睛", "鼻子", "嘴", "耳朵", "手", "脚", "身体", "医生", "医院", "药", "生病", "疼", "健康", "运动", "休息"],
  },
  {
    slug: "home-rooms",
    recommendedProfile: "kids",
    title: "Home & Rooms",
    chineseTitle: "家与房间",
    description: "Practise rooms, furniture, appliances, and other objects children see around the home.",
    age: "Ages 6+",
    level: "Beginner",
    category: "kids",
    words: ["家", "房间", "客厅", "卧室", "厨房", "卫生间", "门", "窗户", "桌子", "椅子", "床", "灯", "电视", "冰箱", "沙发"],
  },
  {
    slug: "transportation",
    recommendedProfile: "adult",
    title: "Transportation",
    chineseTitle: "交通工具",
    description: "Practise vehicles, stations, travel verbs, and simple words for routes and departure.",
    age: "Ages 8+",
    level: "Elementary",
    category: "topics",
    words: ["车", "汽车", "公共汽车", "地铁", "火车", "飞机", "船", "自行车", "出租车", "车站", "机场", "路", "开", "走", "到", "出发"],
  },
  {
    slug: "travel",
    recommendedProfile: "adult",
    title: "Travel",
    chineseTitle: "旅行中文",
    description: "Practise the words needed for passports, tickets, hotels, luggage, directions, and arrival.",
    age: "Teens & Adults",
    level: "Elementary",
    category: "topics",
    words: ["旅行", "旅游", "护照", "地图", "酒店", "房间", "机场", "火车站", "票", "行李", "出发", "到达", "城市", "国家", "照片", "方向"],
  },
  {
    slug: "shopping",
    recommendedProfile: "adult",
    title: "Shopping",
    chineseTitle: "购物中文",
    description: "Practise prices, sizes, colours, clothes, and common words for paying in a shop.",
    age: "Teens & Adults",
    level: "Elementary",
    category: "topics",
    words: ["商店", "超市", "买", "卖", "钱", "元", "块", "贵", "便宜", "多少", "衣服", "鞋", "裤子", "颜色", "大", "小", "现金", "卡"],
  },
  {
    slug: "restaurant",
    recommendedProfile: "adult",
    title: "Restaurant",
    chineseTitle: "餐厅中文",
    description: "Practise menu words, tableware, ordering food, and paying the bill in a restaurant.",
    age: "Teens & Adults",
    level: "Elementary",
    category: "topics",
    words: ["饭馆", "菜单", "点菜", "服务员", "筷子", "碗", "盘子", "米饭", "面条", "菜", "肉", "鱼", "水", "茶", "好吃", "结账"],
  },
  {
    slug: "hobbies-sports",
    recommendedProfile: "adult",
    title: "Hobbies & Sports",
    chineseTitle: "爱好与运动",
    description: "Practise words for sport, music, films, reading, drawing, dancing, and taking photos.",
    age: "Ages 8+",
    level: "Elementary",
    category: "topics",
    words: ["喜欢", "爱好", "运动", "跑步", "游泳", "打球", "篮球", "足球", "羽毛球", "唱歌", "跳舞", "画画", "音乐", "电影", "读书", "拍照"],
  },
  {
    slug: "chinese-new-year",
    recommendedProfile: "adult",
    title: "Chinese New Year",
    chineseTitle: "春节",
    description: "Practise words for New Year greetings, family gatherings, food, and festival activities.",
    age: "All ages",
    level: "Elementary",
    category: "topics",
    words: ["春节", "新年", "快乐", "红包", "灯笼", "饺子", "年糕", "家庭", "团圆", "拜年", "烟花", "龙", "舞狮", "祝福", "传统"],
  },
  {
    slug: "jobs-work",
    recommendedProfile: "adult",
    title: "Jobs & Work",
    chineseTitle: "工作与职业",
    description: "Practise common occupations and the people, places, and roles found at work.",
    age: "Teens & Adults",
    level: "Elementary",
    category: "topics",
    words: ["工作", "公司", "办公室", "老板", "同事", "老师", "医生", "护士", "司机", "服务员", "工人", "商人", "经理", "工程师", "职业"],
  },
];

const p0TemplateDrafts: TemplateDraft[] = [
  {
    slug: "hsk-2",
    recommendedProfile: "adult",
    title: "HSK 2 Writing Practice",
    chineseTitle: "HSK \u4e8c\u7ea7",
    description: "Practise HSK 2 connectors, classroom actions, time words, and short sentence-building vocabulary.",
    age: "Teens & Adults",
    level: "HSK 2",
    category: "hsk",
    words: ["\u65f6\u95f4", "\u95ee\u9898", "\u56e0\u4e3a", "\u6240\u4ee5", "\u4f46\u662f", "\u89c9\u5f97", "\u77e5\u9053", "\u5e2e\u52a9", "\u51c6\u5907", "\u53ef\u80fd", "\u5e94\u8be5", "\u5982\u679c", "\u5df2\u7ecf", "\u4e00\u8d77", "\u516c\u53f8", "\u53bb\u5e74", "\u9ad8\u5174", "\u8fd0\u52a8"],
  },
  {
    slug: "hsk-3",
    recommendedProfile: "adult",
    title: "HSK 3 Writing Practice",
    chineseTitle: "HSK \u4e09\u7ea7",
    description: "Practise HSK 3 transition words, opinions, study terms, and everyday phrases for longer answers.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u867d\u7136", "\u800c\u4e14", "\u53c2\u52a0", "\u5dee\u4e0d\u591a", "\u6210\u7ee9", "\u51fa\u73b0", "\u6253\u7b97", "\u5730\u65b9", "\u53d1\u73b0", "\u653e\u5fc3", "\u6545\u4e8b", "\u8fc7\u53bb", "\u4e00\u5b9a", "\u6700\u8fd1", "\u7ecf\u5e38", "\u660e\u767d", "\u52aa\u529b", "\u76f8\u4fe1"],
  },
  {
    slug: "basic-strokes",
    recommendedProfile: "kids",
    title: "Basic Chinese Strokes",
    chineseTitle: "\u57fa\u672c\u7b14\u753b",
    description: "Practise the core Chinese writing strokes before learners copy full characters in a grid.",
    age: "Ages 4+",
    level: "Beginner",
    category: "kids",
    words: ["\u6a2a", "\u7ad6", "\u6487", "\u637a", "\u70b9", "\u63d0", "\u6298", "\u94a9", "\u5f2f", "\u659c\u94a9", "\u7ad6\u94a9", "\u6a2a\u6298", "\u6a2a\u6487", "\u70b9\u63d0", "\u7ad6\u5f2f\u94a9", "\u5367\u94a9"],
  },
  {
    slug: "radicals",
    recommendedProfile: "adult",
    title: "Chinese Radicals",
    chineseTitle: "\u6c49\u5b57\u90e8\u9996",
    description: "Practise common radical forms that help learners recognise meaning groups inside Chinese characters.",
    age: "Ages 8+",
    level: "Beginner",
    category: "topics",
    words: ["\u4ebb", "\u6c35", "\u624c", "\u8279", "\u5fc4", "\u8ba0", "\u5b80", "\u8fb6", "\u9485", "\u7e9f", "\u9963", "\u72ad", "\u7592", "\u8864", "\u793b", "\u961d", "\u6535", "\u5202", "\u51ab", "\u56d7"],
  },
  {
    slug: "pinyin-practice",
    recommendedProfile: "kids",
    title: "Pinyin and Hanzi Practice",
    chineseTitle: "\u62fc\u97f3\u4e0e\u6c49\u5b57",
    description: "Practise familiar Hanzi with Pinyin shown above each writing row for sound-form review.",
    age: "Ages 6+",
    level: "Beginner",
    category: "topics",
    words: ["\u7231", "\u7238\u7238", "\u676f\u5b50", "\u5317\u4eac", "\u5403", "\u5927", "\u7535\u8111", "\u7535\u89c6", "\u8bfb", "\u5de5\u4f5c", "\u6c49\u8bed", "\u4eca\u5929", "\u8001\u5e08", "\u660e\u5929", "\u670b\u53cb", "\u8bf7", "\u8ba4\u8bc6", "\u5b66\u751f"],
  },
  {
    slug: "stroke-order-practice",
    recommendedProfile: "kids",
    title: "Stroke Order Practice",
    chineseTitle: "\u7b14\u987a\u7ec3\u4e60",
    description: "Practise simple high-frequency characters with stroke-order guidance turned on by default in the worksheet generator.",
    age: "Ages 6+",
    level: "Beginner",
    category: "topics",
    words: ["\u4e00", "\u4e8c", "\u4e09", "\u5341", "\u4eba", "\u53e3", "\u65e5", "\u6708", "\u6728", "\u6c34", "\u706b", "\u5c71", "\u7530", "\u4e2d", "\u5927"],
  },
  {
    slug: "classical-poem-copying",
    recommendedProfile: "adult",
    title: "Classical Poem Copying",
    chineseTitle: "\u53e4\u8bd7\u6284\u5199",
    description: "Copy short classical Chinese poem lines in writing grids for handwriting rhythm and cultural reading practice.",
    age: "Ages 8+",
    level: "Elementary",
    category: "topics",
    words: ["\u6625\u7720\u4e0d\u89c9\u6653", "\u5904\u5904\u95fb\u557c\u9e1f", "\u591c\u6765\u98ce\u96e8\u58f0", "\u82b1\u843d\u77e5\u591a\u5c11", "\u5e8a\u524d\u660e\u6708\u5149", "\u7591\u662f\u5730\u4e0a\u971c", "\u4e3e\u5934\u671b\u660e\u6708", "\u4f4e\u5934\u601d\u6545\u4e61", "\u767d\u65e5\u4f9d\u5c71\u5c3d", "\u9ec4\u6cb3\u5165\u6d77\u6d41", "\u6b32\u7a77\u5343\u91cc\u76ee", "\u66f4\u4e0a\u4e00\u5c42\u697c", "\u9504\u79be\u65e5\u5f53\u5348", "\u6c57\u6ef4\u79be\u4e0b\u571f", "\u8c01\u77e5\u76d8\u4e2d\u9910", "\u7c92\u7c92\u7686\u8f9b\u82e6"],
  },
];

const mvpTemplateDrafts: TemplateDraft[] = [
  {
    slug: "hsk-3-campus-life",
    recommendedProfile: "adult",
    title: "HSK 3 Campus Life",
    seoTitle: "HSK 3 Campus Life Chinese Worksheet",
    seoDescription: "Edit and print an HSK 3 campus life worksheet with school, classroom, exam, and study vocabulary for Chinese writing practice.",
    h1: "HSK 3 Campus Life Chinese Worksheet",
    chineseTitle: "HSK 3 \u6821\u56ed\u751f\u6d3b",
    description: "Practise HSK 3 school, classroom, exam, and study words for campus-life writing tasks.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u5927\u5b66\u751f", "\u6559\u5e08", "\u653e\u5b66", "\u6559\u5ba4", "\u4e0a\u8bfe", "\u4e0b\u8bfe", "\u73ed", "\u8003\u8bd5", "\u5206\u6570", "\u7ec3", "\u590d\u4e60", "\u53c2\u52a0", "\u8bf7", "\u6c49\u8bed", "\u666e\u901a\u8bdd", "\u672c\u5b50", "\u7b54\u5e94", "\u95ee\u9898"],
  },
  {
    slug: "hsk-3-health",
    recommendedProfile: "adult",
    title: "HSK 3 Health",
    seoTitle: "HSK 3 Health Chinese Writing Practice",
    seoDescription: "Create an editable HSK 3 health writing practice sheet with body, doctor, hospital, exercise, and care vocabulary.",
    h1: "HSK 3 Health Chinese Writing Practice",
    chineseTitle: "HSK 3 \u5065\u5eb7",
    description: "Practise health, body, hospital, and care words for HSK 3 handwriting review.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u5065\u5eb7", "\u770b\u75c5", "\u51fa\u9662", "\u751f\u75c5", "\u533b\u751f", "\u533b\u9662", "\u773c", "\u624b", "\u811a", "\u5934", "\u53e3", "\u6d17", "\u6c34", "\u8dd1\u6b65", "\u8fd0\u52a8", "\u4f11\u606f", "\u5fc3", "\u8eab\u4f53"],
  },
  {
    slug: "hsk-3-shopping-money",
    recommendedProfile: "adult",
    title: "HSK 3 Shopping & Money",
    seoTitle: "HSK 3 Shopping and Money Worksheet",
    seoDescription: "Make a printable HSK 3 shopping and money worksheet with price, clothing, color, payment, and store vocabulary.",
    h1: "HSK 3 Shopping and Money Worksheet",
    chineseTitle: "HSK 3 \u8d2d\u7269\u4e0e\u94b1",
    description: "Practise shopping, money, size, colour, and payment words for everyday HSK 3 errands.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u5546\u5e97", "\u4e70", "\u5356", "\u94b1", "\u8d35", "\u5546\u573a", "\u8863\u670d", "\u7ea2\u8272", "\u9009", "\u7a7f", "\u4fe1\u7528\u5361", "\u4ea4\u7ed9", "\u5927", "\u5c0f", "\u7528", "\u8981", "\u7ed9", "\u989c\u8272"],
  },
  {
    slug: "hsk-3-technology",
    recommendedProfile: "adult",
    title: "HSK 3 Technology",
    seoTitle: "HSK 3 Technology Chinese Worksheet",
    seoDescription: "Build an HSK 3 technology Chinese worksheet for phone, computer, website, media, message, and online study words.",
    h1: "HSK 3 Technology Chinese Worksheet",
    chineseTitle: "HSK 3 \u79d1\u6280\u751f\u6d3b",
    description: "Practise phone, computer, website, message, and media words for digital-life handwriting.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u624b\u673a", "\u7535\u8111", "\u7f51\u7ad9", "\u4fe1\u606f", "\u6253\u7535\u8bdd", "\u62a5\u7eb8", "\u7167\u76f8", "\u76f8\u673a", "\u6253\u5f00", "\u5173", "\u4f7f\u7528", "\u5b66", "\u6253\u5de5", "\u7535\u89c6", "\u7535\u5f71", "\u4e0a\u7f51", "\u753b", "\u65b0\u95fb"],
  },
  {
    slug: "hsk-3-exams-grades",
    recommendedProfile: "adult",
    title: "HSK 3 Exams & Grades",
    seoTitle: "HSK 3 Exam and Grade Writing Worksheet",
    seoDescription: "Print an HSK 3 exam and grade writing worksheet with review, score, reading, dictation, and correction vocabulary.",
    h1: "HSK 3 Exam and Grade Writing Worksheet",
    chineseTitle: "HSK 3 \u8003\u8bd5\u4e0e\u6210\u7ee9",
    description: "Practise exam, score, review, listening, reading, and correction words for HSK 3 study sheets.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u8003\u8bd5", "\u5206\u6570", "\u73ed", "\u590d\u4e60", "\u7ec3", "\u53c2\u52a0", "\u5ea6", "\u8bb0\u5f97", "\u5fd8", "\u660e\u767d", "\u8bf7", "\u4e0d\u9519", "\u9519", "\u542c\u5199", "\u8bfb", "\u7b54\u5e94", "\u95ee\u9898", "\u6210\u7ee9"],
  },
  {
    slug: "hsk-3-apartment-home",
    recommendedProfile: "adult",
    title: "HSK 3 Apartment & Home",
    seoTitle: "HSK 3 Home and Apartment Worksheet",
    seoDescription: "Edit an HSK 3 home and apartment worksheet with room, furniture, floor, inside, outside, and home-life words.",
    h1: "HSK 3 Home and Apartment Worksheet",
    chineseTitle: "HSK 3 \u5bb6\u4e0e\u623f\u95f4",
    description: "Practise room, furniture, floor, inside, outside, and home-life words for HSK 3 writing.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u623f\u95f4", "\u6905\u5b50", "\u5e8a", "\u751f\u6d3b", "\u5b89\u9759", "\u56de\u56fd", "\u623f\u5b50", "\u5173\u4e0a", "\u91cc", "\u5916", "\u697c\u4e0a", "\u697c\u4e0b", "\u697c", "\u5bb6", "\u95e8", "\u684c\u5b50", "\u4f4f", "\u9762"],
  },
  {
    slug: "hsk-3-office-teamwork",
    recommendedProfile: "adult",
    title: "HSK 3 Office Teamwork",
    seoTitle: "HSK 3 Workplace Chinese Worksheet",
    seoDescription: "Create an HSK 3 workplace Chinese worksheet with office, company, manager, colleague, meeting, and teamwork vocabulary.",
    h1: "HSK 3 Workplace Chinese Worksheet",
    chineseTitle: "HSK 3 \u529e\u516c\u4e0e\u5408\u4f5c",
    description: "Practise office, company, plan, manager, colleague, and discussion words for workplace Chinese.",
    age: "Teens & Adults",
    level: "HSK 3",
    category: "hsk",
    words: ["\u7ecf\u7406", "\u529e\u516c\u5ba4", "\u6253\u7b97", "\u5e2e", "\u516c\u53f8", "\u6253\u5de5", "\u4e3e\u884c", "\u505a\u996d", "\u96be\u9898", "\u61c2\u5f97", "\u5b8c", "\u6253\u7535\u8bdd", "\u4e00\u5171", "\u540c\u4e8b", "\u8ba8\u8bba", "\u8ba1\u5212", "\u95ee\u9898", "\u4e00\u8d77"],
  },
  {
    slug: "top-100-chinese-characters",
    recommendedProfile: "adult",
    title: "Top 100 Chinese Characters",
    seoTitle: "Top 100 Chinese Characters Writing Practice",
    seoDescription: "Practise the top 100 Chinese characters with an editable writing practice sheet, tracing rows, Pinyin, and printable PDF output.",
    h1: "Top 100 Chinese Characters Writing Practice",
    chineseTitle: "\u5e38\u7528\u6c49\u5b57 100",
    description: "Practise a compact set of high-frequency Chinese characters for recognition, tracing, and recall.",
    age: "Teens & Adults",
    level: "Beginner",
    category: "topics",
    words: top100ChineseCharacterWords,
  },
  {
    slug: "blank-tianzige-grid",
    recommendedProfile: "kids",
    title: "Blank Tian Zi Ge Grid",
    seoTitle: "Printable Tian Zi Ge Paper Generator",
    seoDescription: "Generate printable Tian Zi Ge paper, add Chinese characters, edit the grid practice rows, and download a handwriting PDF.",
    h1: "Printable Tian Zi Ge Practice Paper",
    chineseTitle: "\u7530\u5b57\u683c\u7ec3\u4e60\u7eb8",
    description: "Start from a simple Tian Zi Ge handwriting grid and edit the words before printing.",
    age: "Ages 4+",
    level: "Beginner",
    category: "kids",
    words: ["\u4e00", "\u4e8c", "\u4e09", "\u5341", "\u4eba", "\u53e3", "\u65e5", "\u6708", "\u6728", "\u6c34", "\u706b", "\u5c71", "\u7530", "\u4e2d", "\u5927", "\u5c0f", "\u4e0a", "\u4e0b"],
  },
  {
    slug: "chinese-first-characters",
    recommendedProfile: "kids",
    title: "Chinese First Characters",
    seoTitle: "First Chinese Characters Worksheet",
    seoDescription: "Print a first Chinese characters worksheet for young beginners with simple Hanzi, tracing rows, Pinyin, and editable practice grids.",
    h1: "First Chinese Characters Worksheet",
    chineseTitle: "\u5165\u95e8\u6c49\u5b57",
    description: "Practise the first simple Chinese characters most beginners meet before longer vocabulary lists.",
    age: "Ages 4+",
    level: "Beginner",
    category: "kids",
    words: top100ChineseCharacterWords.slice(0, 24),
  },
  {
    slug: "hsk-4",
    recommendedProfile: "adult",
    title: "HSK 4 Writing Practice",
    seoTitle: "HSK 4 Chinese Writing Worksheet",
    seoDescription: "Edit and print an HSK 4 Chinese writing worksheet with society, culture, environment, education, and opinion vocabulary.",
    h1: "HSK 4 Chinese Writing Worksheet",
    chineseTitle: "HSK \u56db\u7ea7",
    description: "Practise HSK 4 words for society, culture, study, opinions, and everyday written answers.",
    age: "Teens & Adults",
    level: "HSK 4",
    category: "hsk",
    words: ["\u793e\u4f1a", "\u6587\u5316", "\u7ecf\u6d4e", "\u73af\u5883", "\u6559\u80b2", "\u79d1\u6280", "\u653f\u5e9c", "\u5386\u53f2", "\u53d1\u5c55", "\u5f71\u54cd", "\u7ecf\u9a8c", "\u673a\u4f1a", "\u91cd\u8981", "\u89e3\u51b3", "\u9009\u62e9", "\u4fdd\u62a4", "\u8d23\u4efb", "\u89c2\u70b9"],
  },
  {
    slug: "hsk-5",
    recommendedProfile: "adult",
    title: "HSK 5 Writing Practice",
    seoTitle: "HSK 5 Chinese Writing Worksheet",
    seoDescription: "Create an editable HSK 5 Chinese writing worksheet for management, research, market, data, trend, and cooperation vocabulary.",
    h1: "HSK 5 Chinese Writing Worksheet",
    chineseTitle: "HSK \u4e94\u7ea7",
    description: "Practise HSK 5 abstract and workplace words for longer Chinese writing and review.",
    age: "Teens & Adults",
    level: "HSK 5",
    category: "hsk",
    words: ["\u6761\u4ef6", "\u63d0\u9ad8", "\u7ba1\u7406", "\u7814\u7a76", "\u6539\u53d8", "\u8054\u7cfb", "\u56fd\u9645", "\u4f20\u7edf", "\u73b0\u4ee3", "\u8d44\u6e90", "\u538b\u529b", "\u91c7\u53d6", "\u7279\u70b9", "\u5efa\u8bae", "\u53cd\u5bf9", "\u652f\u6301", "\u4fdd\u6301", "\u7ed3\u679c", "\u539f\u56e0", "\u8fc7\u7a0b", "\u6807\u51c6", "\u80fd\u529b", "\u54c1\u724c", "\u5e02\u573a", "\u6d88\u8d39", "\u670d\u52a1", "\u8d28\u91cf", "\u9879\u76ee", "\u60c5\u51b5", "\u6570\u636e", "\u8d8b\u52bf", "\u5408\u4f5c"],
  },
  {
    slug: "top-200-chinese-characters",
    recommendedProfile: "adult",
    title: "Top 200 Chinese Characters",
    seoTitle: "Top 200 Chinese Characters Writing Practice",
    seoDescription: "Practise the top 200 Chinese characters with an editable handwriting worksheet, tracing rows, Pinyin, and printable PDF output.",
    h1: "Top 200 Chinese Characters Writing Practice",
    chineseTitle: "\u5e38\u7528\u6c49\u5b57 200",
    description: "Practise a broader set of high-frequency Chinese characters for recognition and handwriting review.",
    age: "Teens & Adults",
    level: "Beginner",
    category: "topics",
    words: top200ChineseCharacterWords,
  },
  {
    slug: "blank-mi-zi-ge-grid",
    recommendedProfile: "kids",
    title: "Blank Mi Zi Ge Grid",
    seoTitle: "Printable Mi Zi Ge Paper Generator",
    seoDescription: "Generate printable Mi Zi Ge paper, edit the starter Chinese characters, change practice rows, and download a handwriting PDF.",
    h1: "Printable Mi Zi Ge Practice Paper",
    chineseTitle: "\u7c73\u5b57\u683c\u7ec3\u4e60\u7eb8",
    description: "Start from a Mi Zi Ge handwriting grid and replace the starter characters before printing.",
    age: "Ages 4+",
    level: "Beginner",
    category: "kids",
    words: ["\u4e00", "\u4e8c", "\u4e09", "\u5341", "\u4eba", "\u53e3", "\u65e5", "\u6708", "\u6728", "\u6c34", "\u706b", "\u5c71", "\u7530", "\u4e2d", "\u5927", "\u5c0f", "\u4e0a", "\u4e0b"],
  },
  {
    slug: "chinese-numbers-1-100",
    recommendedProfile: "kids",
    title: "Chinese Numbers 1-100",
    seoTitle: "Chinese Numbers 1-100 Writing Practice",
    seoDescription: "Print a Chinese numbers 1-100 writing practice sheet with number characters, tens, one hundred, Pinyin, and editable rows.",
    h1: "Chinese Numbers 1-100 Writing Practice",
    chineseTitle: "\u4e2d\u6587\u6570\u5b57 1-100",
    description: "Practise Chinese numbers from one to one hundred, including tens and useful number patterns.",
    age: "Ages 6+",
    level: "Beginner",
    category: "kids",
    words: ["\u4e00", "\u4e8c", "\u4e09", "\u56db", "\u4e94", "\u516d", "\u4e03", "\u516b", "\u4e5d", "\u5341", "\u4e8c\u5341", "\u4e09\u5341", "\u56db\u5341", "\u4e94\u5341", "\u516d\u5341", "\u4e03\u5341", "\u516b\u5341", "\u4e5d\u5341", "\u4e00\u767e"],
  },
  {
    slug: "chinese-measure-words",
    recommendedProfile: "adult",
    title: "Chinese Measure Words",
    seoTitle: "Chinese Measure Words Worksheet",
    seoDescription: "Create a printable Chinese measure words worksheet with common classifiers for people, books, flat objects, animals, cups, pairs, and vehicles.",
    h1: "Chinese Measure Words Worksheet",
    chineseTitle: "\u4e2d\u6587\u91cf\u8bcd",
    description: "Practise common Chinese measure words and short number-classifier phrases for classroom review.",
    age: "Ages 8+",
    level: "Elementary",
    category: "topics",
    words: ["\u4e2a", "\u4f4d", "\u540d", "\u672c", "\u5f20", "\u53ea", "\u6761", "\u4ef6", "\u676f", "\u53cc", "\u53e3", "\u5bb6", "\u8f86", "\u6240", "\u5ea7", "\u5757", "\u6b21", "\u4e00\u4e2a", "\u4e24\u4e2a", "\u4e09\u672c", "\u56db\u5f20", "\u4e94\u53ea", "\u516d\u6761", "\u4e03\u4ef6", "\u516b\u676f", "\u4e5d\u53cc", "\u5341\u53e3"],
  },
  {
    slug: "common-chinese-verbs",
    recommendedProfile: "adult",
    title: "Common Chinese Verbs",
    seoTitle: "Common Chinese Verbs Worksheet",
    seoDescription: "Edit and print a common Chinese verbs worksheet with everyday action words for speaking, reading, writing, shopping, travel, and classroom practice.",
    h1: "Common Chinese Verbs Worksheet",
    chineseTitle: "\u5e38\u7528\u4e2d\u6587\u52a8\u8bcd",
    description: "Practise everyday Chinese verbs for classroom actions, movement, shopping, study, and daily routines.",
    age: "Ages 8+",
    level: "Beginner",
    category: "topics",
    words: ["\u505a", "\u770b", "\u542c", "\u8bf4", "\u5199", "\u8bfb", "\u95ee", "\u56de\u7b54", "\u5b66", "\u6559", "\u4e70", "\u5356", "\u5f00", "\u5173", "\u6765", "\u53bb", "\u8d70", "\u8dd1", "\u5403", "\u559d", "\u7ed9", "\u627e", "\u7528", "\u60f3", "\u559c\u6b22", "\u5e2e", "\u7b49", "\u5b8c", "\u8fdb", "\u51fa", "\u8d77", "\u4f4f", "\u5750", "\u7ad9", "\u7b11", "\u54ed", "\u89c9\u5f97", "\u77e5\u9053", "\u660e\u767d", "\u51b3\u5b9a", "\u5e0c\u671b", "\u53ef\u4ee5", "\u5e94\u8be5", "\u53d1\u73b0", "\u53c2\u52a0", "\u7ec3\u4e60"],
  },
];

const templateGuidance: Record<string, TemplateGuidance> = {
  family: {
    learningGoal: "Learners recognise and write common family titles, then connect each Hanzi word with the person it describes in everyday introductions.",
    teachingTip: "Group the words by immediate and extended family before writing. This gives younger learners a simple meaning pattern instead of one long list to memorise.",
    practiceActivity: "Ask learners to draw a small family tree, label each person with one word from the sheet, and finish by introducing two relatives aloud.",
  },
  numbers: {
    learningGoal: "Learners write the core Chinese number characters accurately and use them as building blocks for larger numbers, dates, ages, and classroom counting.",
    teachingTip: "Practise zero to ten first, then combine familiar characters into new numbers. Say each number aloud before tracing so sound, meaning, and form stay connected.",
    practiceActivity: "Call out five numbers in a mixed order for students to write, then let them create a date, age, or price using the same characters.",
  },
  colors: {
    learningGoal: "Learners identify and write common Chinese colour words, including the shorter forms used when colours describe familiar classroom and household objects.",
    teachingTip: "Pair every colour with a real object or coloured card. Contrast two colours at a time so learners attach each written form to a visible meaning.",
    practiceActivity: "Students choose five objects nearby, write the matching colour beside each object name, and read the completed colour phrases to a partner.",
  },
  greetings: {
    learningGoal: "Learners write and distinguish greetings, thanks, apologies, and polite expressions they can reuse when meeting, helping, or leaving another speaker.",
    teachingTip: "Teach the phrases in short conversational pairs rather than isolation. Learners remember the writing more easily when each expression has a clear response.",
    practiceActivity: "Put learners in pairs to choose a greeting, a polite question, and a closing phrase, then copy and perform their three-line exchange.",
  },
  "days-months": {
    learningGoal: "Learners write weekday, month, and relative-time words and use them to recognise how Chinese dates and simple calendar statements are assembled.",
    teachingTip: "Keep a calendar visible while students write. Point out repeated components such as 星期 and 月 so the longer words feel like predictable combinations.",
    practiceActivity: "Students write today, tomorrow, and one planned date, then swap papers and read their partner's three calendar expressions aloud.",
  },
  "food-drinks": {
    learningGoal: "Learners recognise and write everyday foods, drinks, fruit, and meal words that support simple choices, preferences, and classroom menu conversations.",
    teachingTip: "Sort the vocabulary into food, drink, and meal groups before tracing. Invite learners to mark familiar items so the first practice round starts with meaning they know.",
    practiceActivity: "Learners design a three-item meal, copy the selected food and drink words, and use the finished list to tell a partner what they would choose.",
  },
  "animals-kids": {
    learningGoal: "Younger learners recognise and write familiar pet, farm, bird, and zoo animal words while connecting each written form to a concrete creature.",
    teachingTip: "Use animal pictures or sounds before showing the Hanzi. Let learners predict the animal, then trace its word while repeating the pronunciation slowly.",
    practiceActivity: "Students sort six animals into home, farm, or zoo groups, write one word in each group, and explain which animal they like best.",
  },
  "hsk-1": {
    learningGoal: "Beginning HSK learners build accurate recall of high-frequency pronouns, verbs, people, places, and classroom words required for basic reading and writing.",
    teachingTip: "Divide the list into small semantic sets and review one set at a time. Alternate tracing with no-model recall so recognition develops into independent writing.",
    practiceActivity: "Choose ten words for a timed review: trace each once, hide the model, write it again from Pinyin or English, and circle items needing another round.",
  },
  "school-classroom": {
    learningGoal: "Learners write the people, objects, instructions, and tasks they encounter in school, making classroom Chinese easier to recognise and use.",
    teachingTip: "Point to real classroom objects and actions while introducing their words. Physical context prevents similar-looking new characters from becoming an abstract list.",
    practiceActivity: "Students label five classroom objects, copy two instruction words, and use the completed sheet for a short classroom scavenger hunt.",
  },
  "daily-routine": {
    learningGoal: "Learners write common actions from waking to bedtime and organise them into a meaningful sequence for describing an ordinary day.",
    teachingTip: "Arrange the words chronologically before handwriting practice. Ask learners to compare the list with their own routine and replace unfamiliar activities when useful.",
    practiceActivity: "Students select six routine words, number them in personal order, write each one, and use the sequence to describe their day to a partner.",
  },
  "weather-seasons": {
    learningGoal: "Learners recognise and write weather conditions, temperature descriptions, and season names used in forecasts and everyday observations.",
    teachingTip: "Begin with the day's real weather and current season. Contrast hot with cold and rain with snow before adding less immediate forecast vocabulary.",
    practiceActivity: "Students create a three-day mini forecast by choosing weather and temperature words, writing them beside each day, and presenting the forecast aloud.",
  },
  "body-health": {
    learningGoal: "Learners write key body parts, health states, and care words needed to describe simple symptoms and understand basic help-seeking language.",
    teachingTip: "Separate body-part words from symptoms and places of care. Use neutral examples and allow learners to skip personal health details while practising the language.",
    practiceActivity: "Students match four body words with simple health statements, copy the key vocabulary, and role-play asking where something hurts.",
  },
  "home-rooms": {
    learningGoal: "Learners recognise and write rooms, furniture, appliances, and household objects used when describing where things are at home.",
    teachingTip: "Organise the list room by room and begin with the learner's own home. Spatial grouping makes the vocabulary easier to retrieve than alphabetical order.",
    practiceActivity: "Students sketch one room, label at least five objects with words from the sheet, and describe where two items are located.",
  },
  transportation: {
    learningGoal: "Learners write common vehicles, stations, travel actions, and route words used to discuss how someone leaves, travels, and arrives.",
    teachingTip: "Group vehicles separately from places and actions, then recombine them in short travel chains. Compare similar transport words only after each is familiar.",
    practiceActivity: "Students plan a simple journey with one vehicle, one station, and two action words, then copy and explain the route in sequence.",
  },
  travel: {
    learningGoal: "Learners write practical words for documents, tickets, hotels, luggage, directions, departure, and arrival during an everyday trip.",
    teachingTip: "Teach the vocabulary through a journey timeline from preparation to arrival. Let learners mark the words they would need at each travel stage.",
    practiceActivity: "Students pack a fictional trip by selecting eight words, writing them as a checklist, and using three of them in a short travel request.",
  },
  shopping: {
    learningGoal: "Learners write words for shops, prices, sizes, colours, clothing, and payment so they can follow a simple buying conversation.",
    teachingTip: "Use price tags and two contrasting items to practise choice language. Review number and colour characters before introducing the full shopping set.",
    practiceActivity: "Students create two product cards with item, colour, size, and price words, then exchange cards and practise asking which item a partner wants.",
  },
  restaurant: {
    learningGoal: "Learners write menu, tableware, ordering, food, drink, and payment words that appear during a basic restaurant visit.",
    teachingTip: "Arrange the words in service order: arrival, menu, order, meal, and bill. Rehearse only a few items at each stage before combining them.",
    practiceActivity: "Students make a small menu with one drink and three foods, write a sample order, and role-play requesting the bill after the meal.",
  },
  "hobbies-sports": {
    learningGoal: "Learners write activity words for sport, music, film, reading, art, dance, and photography when discussing personal interests.",
    teachingTip: "Ask learners to sort activities into like, dislike, and want-to-try groups. Personal choices create a stronger reason to remember each written word.",
    practiceActivity: "Students choose three hobbies they enjoy and one they want to try, write the four words, and compare their choices with a partner.",
  },
  "chinese-new-year": {
    learningGoal: "Learners write Chinese New Year greetings, foods, family gathering words, decorations, and festival activities in their cultural context.",
    teachingTip: "Introduce the vocabulary with photos or personal stories and distinguish greetings from objects and activities. Explain regional variation where it affects meaning.",
    practiceActivity: "Students design a small New Year card using one greeting and three festival words, then explain the meaning of each selected item.",
  },
  "jobs-work": {
    learningGoal: "Learners write common occupations, workplaces, colleagues, and role words used to ask about or describe what someone does.",
    teachingTip: "Group occupations by workplace or service instead of memorising a flat list. Point out when one person word can appear in several professional contexts.",
    practiceActivity: "Students select four occupations, match each with a workplace or task, write the pairs, and use one pair to describe a fictional person.",
  },
};

const p0TemplateGuidance: Record<string, TemplateGuidance> = {
  "hsk-2": {
    learningGoal: "Learners write common HSK 2 words accurately and use connectors such as because, therefore, but, and if to prepare for short sentence practice.",
    teachingTip: "Split the words into function words, study words, and daily-life words before writing. Learners should say one example sentence aloud before copying each connector.",
    practiceActivity: "Students choose six words, write each one twice, then combine at least two connectors into a short written answer about school, work, or last year.",
  },
  "hsk-3": {
    learningGoal: "Learners practise HSK 3 words that support opinions, transitions, plans, and study reflection so handwriting review also strengthens longer written responses.",
    teachingTip: "Pair similar functions together, such as although and also or plan and discover. Short comparison groups help learners remember usage while they trace the forms.",
    practiceActivity: "Ask learners to copy eight words, mark the ones they can use in a full sentence, and write two original HSK-style sentences after the tracing rows.",
  },
  "basic-strokes": {
    learningGoal: "Learners build control of the core Chinese stroke shapes before moving into complete Hanzi, improving direction, proportion, and grid placement.",
    teachingTip: "Demonstrate one stroke direction at a time and keep the first round slow. Stroke names are less important than starting point, ending point, and pressure rhythm.",
    practiceActivity: "Students trace each stroke, circle the one that feels hardest, and use three selected strokes to build a simple character such as one, ten, or big.",
  },
  radicals: {
    learningGoal: "Learners recognise common radical forms and practise writing them as reusable building blocks that appear inside many Chinese characters.",
    teachingTip: "Teach radicals as shape clues, not full definitions. Show one or two example characters beside each radical only after learners have copied the radical form.",
    practiceActivity: "Students sort radicals into meaning groups, write five selected radicals again, and then find one character on the worksheet or in class that uses each form.",
  },
  "pinyin-practice": {
    learningGoal: "Learners connect familiar Hanzi forms with Pinyin readings while handwriting, strengthening sound-form recall before they practise without Pinyin support.",
    teachingTip: "Read each row aloud before tracing. Keep Pinyin visible for the first pass, then open the generator and switch to a test-style page for recall practice.",
    practiceActivity: "Students cover the Hanzi column, read the Pinyin, write the character from memory, and compare their result with the model row after each attempt.",
  },
  "stroke-order-practice": {
    learningGoal: "Learners practise high-frequency simple characters with stroke-order support, building habits they can transfer to larger compound words and templates.",
    teachingTip: "Keep stroke order visible at first and ask learners to air-write the sequence before using the pencil. Remove the guide only after the sequence feels stable.",
    practiceActivity: "Students trace the model once, write the character twice with stroke order visible, then hide the guide and try one final blank-grid copy.",
  },
  "classical-poem-copying": {
    learningGoal: "Learners copy short classical poem lines in balanced writing grids, practising rhythm, spacing, and familiar cultural texts without needing a full poem lesson.",
    teachingTip: "Read one couplet aloud before handwriting and explain only the gist. The goal is controlled copying and line rhythm, not a detailed literary analysis.",
    practiceActivity: "Students choose one four-line poem section, copy each line slowly, then read the copied lines aloud and mark the character that needs the most review.",
  },
};

const mvpTemplateGuidance: Record<string, TemplateGuidance> = {
  "hsk-3-campus-life": {
    learningGoal: "Learners practise school, classroom, and exam words that help them write short HSK 3 sentences about daily study routines and campus activities.",
    teachingTip: "Group the words into people, places, actions, and exam results before handwriting. The meaning groups make the campus scene easier to remember than a flat list.",
    practiceActivity: "Students choose six words to describe one school day, copy each word twice, and then write a two-sentence campus-life summary with at least three selected words.",
  },
  "hsk-3-health": {
    learningGoal: "Learners write common health, body, doctor, hospital, and exercise words so they can recognise and copy simple health-related HSK 3 prompts.",
    teachingTip: "Keep the examples neutral and practical. Start with body and care words before asking learners to copy words about illness, hospital visits, or recovery.",
    practiceActivity: "Students mark five health words they could use in a clinic conversation, copy those words again, and write one short request for help or rest.",
  },
  "hsk-3-shopping-money": {
    learningGoal: "Learners practise shopping and money words for prices, choices, colours, payment, and common buying actions used in everyday HSK 3 errands.",
    teachingTip: "Use a simple product card or price tag while learners write. Pair money words with clothing or colour words so the list feels like a real shopping task.",
    practiceActivity: "Students create two small shopping cards, copy the item, colour, and payment words, and then choose which card is cheaper or more useful.",
  },
  "hsk-3-technology": {
    learningGoal: "Learners write technology and media words for phones, computers, websites, photos, calls, and online study so digital-life vocabulary becomes easier to recall.",
    teachingTip: "Connect each word to one visible action such as opening a phone, taking a photo, reading news, or using a website before the tracing round begins.",
    practiceActivity: "Students select four technology words they used today, copy each word twice, and write a short note about how they studied or communicated online.",
  },
  "hsk-3-exams-grades": {
    learningGoal: "Learners practise exam, score, review, correction, reading, and dictation words that support HSK 3 study reflection and test-preparation writing.",
    teachingTip: "Separate preparation words from result words. This lets learners practise a before-and-after exam story rather than memorising isolated school terms.",
    practiceActivity: "Students copy the review and result words, circle three words that describe their last test, and write one sentence about what improved or needs review.",
  },
  "hsk-3-apartment-home": {
    learningGoal: "Learners write home, room, furniture, floor, inside, and outside words for describing where people live and where objects are placed.",
    teachingTip: "Ask learners to picture one apartment or classroom corner while writing. Spatial vocabulary becomes easier when every word has a visible location.",
    practiceActivity: "Students sketch a small room, label five places or objects with copied words, and then describe one item as upstairs, downstairs, inside, or outside.",
  },
  "hsk-3-office-teamwork": {
    learningGoal: "Learners practise workplace words for office, company, manager, colleague, planning, phone calls, and discussion before writing short teamwork statements.",
    teachingTip: "Treat the list as a workday sequence: plan, discuss, call, help, finish. Sequencing gives adult learners a practical reason to remember each written form.",
    practiceActivity: "Students choose one project situation, copy eight workplace words, and use three of them to write a short note about finishing work together.",
  },
  "top-100-chinese-characters": {
    learningGoal: "Learners review high-frequency standalone Chinese characters and strengthen recall before moving into longer HSK words, phrases, and sentence copying.",
    teachingTip: "Do not rush the full set in one sitting. Split the sheet into smaller rounds and ask learners to mark characters they recognise before tracing.",
    practiceActivity: "Students copy twenty characters from one section, hide the model row, rewrite ten from memory, and keep a short review list for the next practice sheet.",
  },
  "blank-tianzige-grid": {
    learningGoal: "Learners begin with a simple Tian Zi Ge grid and a small starter set of easy characters, then edit the list into a blank or custom handwriting sheet.",
    teachingTip: "Use this page when the main goal is grid control. Open the generator, delete rows if a blank grid is needed, or replace the starter characters with class words.",
    practiceActivity: "Students trace the starter characters once, then open the generator to replace three rows with current lesson words and print the customised grid.",
  },
  "chinese-first-characters": {
    learningGoal: "Young beginners practise a small first-character set with simple shapes and high reuse value before they copy longer words or themed vocabulary.",
    teachingTip: "Introduce only a few characters at a time and connect each one to a gesture, number, person, or classroom object before handwriting starts.",
    practiceActivity: "Students choose six familiar characters, copy each one slowly, and point to one real object or idea that matches each selected character.",
  },
  "hsk-4": {
    learningGoal: "Learners practise HSK 4 words for society, culture, education, environment, and opinion writing so handwriting review supports longer Chinese answers.",
    teachingTip: "Group the abstract words into topics before writing. Ask learners to say one short opinion or reason aloud before copying each selected vocabulary item.",
    practiceActivity: "Students choose eight HSK 4 words, copy each word twice, then write two short opinion sentences using one reason word and one topic word.",
  },
  "hsk-5": {
    learningGoal: "Learners review HSK 5 abstract and workplace vocabulary for management, research, markets, data, trends, and cooperation while strengthening character recall.",
    teachingTip: "Treat the list as advanced review rather than first exposure. Let learners mark useful words for essays, then practise those words before the full sheet.",
    practiceActivity: "Students select ten words for one study or work topic, copy them in groups, and write a short paragraph outline using at least five selected terms.",
  },
  "top-200-chinese-characters": {
    learningGoal: "Learners broaden high-frequency character recall beyond the first hundred characters and prepare for more flexible word, phrase, and sentence practice.",
    teachingTip: "Split the set into smaller batches and avoid assigning all 200 characters at once. Use the generator to print a focused review section when needed.",
    practiceActivity: "Students copy one batch of twenty characters, circle unfamiliar items, and create a short personal review list for the next printable worksheet.",
  },
  "blank-mi-zi-ge-grid": {
    learningGoal: "Learners use Mi Zi Ge guide lines to control stroke angle, centre balance, and character proportions before moving into free writing or larger grids.",
    teachingTip: "Use this page for shape control rather than vocabulary load. Replace the starter rows with current class words or delete rows for a mostly blank grid.",
    practiceActivity: "Students write five simple characters in Mi Zi Ge, compare centre placement, and reprint the sheet with only the characters that need correction.",
  },
  "chinese-numbers-1-100": {
    learningGoal: "Learners write Chinese numbers from one to one hundred and recognise the repeated patterns used for tens, dates, ages, prices, and classroom counting.",
    teachingTip: "Practise one to ten first, then show how tens are built from familiar characters. Keep oral counting connected to writing so patterns stay obvious.",
    practiceActivity: "Students copy the tens, write three ages or prices from dictation, and then create five number questions for a partner to read aloud.",
  },
  "chinese-measure-words": {
    learningGoal: "Learners practise common Chinese measure words and number-classifier phrases used with people, books, objects, animals, cups, pairs, vehicles, and places.",
    teachingTip: "Pair every measure word with a concrete noun or classroom object. Avoid teaching classifiers as a flat grammar list without examples learners can see.",
    practiceActivity: "Students match ten objects to measure words, copy the classifier phrases, and write three new phrases using objects from the classroom.",
  },
  "common-chinese-verbs": {
    learningGoal: "Learners build handwriting recall for everyday Chinese verbs used in classroom actions, movement, shopping, study, routines, decisions, and communication.",
    teachingTip: "Sort the verbs by action type before tracing. Let learners mime or say a simple sentence with each group so writing connects to real usage.",
    practiceActivity: "Students pick six verbs from two groups, copy each one twice, and write a mini daily routine or classroom instruction list with the selected verbs.",
  },
};

function addTemplateGuidance(
  template: WorksheetTemplateSeed,
): WorksheetTemplate {
  const guidance =
    templateGuidance[template.slug] ??
    p0TemplateGuidance[template.slug] ??
    mvpTemplateGuidance[template.slug];
  if (!guidance) {
    throw new Error(`Missing template guidance for ${template.slug}`);
  }
  return { ...template, ...guidance };
}

function buildTemplate(draft: TemplateDraft): WorksheetTemplate {
  const { words, ...metadata } = draft;
  const entries = entriesFor(words);
  return addTemplateGuidance({
    ...metadata,
    entries,
    wordCount: entries.length,
  });
}

export const worksheetTemplates: WorksheetTemplate[] = [
  ...baseWorksheetTemplates.map((template) => {
    const words = expandedTemplateWords[template.slug];
    if (!words) {
      return addTemplateGuidance({
        ...template,
        wordCount: template.entries.length,
      });
    }
    const entries = entriesFor(words);
    return addTemplateGuidance({
      ...template,
      entries,
      wordCount: entries.length,
    });
  }),
  ...additionalTemplateDrafts.map(buildTemplate),
  ...p0TemplateDrafts.map(buildTemplate),
  ...mvpTemplateDrafts.map(buildTemplate),
];
