import type { StrokeOrderCharacter, StrokeOrderHskCard } from "./stroke-order-characters";

type GuideSeed = Omit<StrokeOrderCharacter, "hsk" | "seo" | "publicationStatus"> & {
  hsk20?: "1" | "2";
  hsk30: "1";
  seoDescription: string;
};

function hsk(character: string, system: "2.0" | "3.0", level: string): StrokeOrderHskCard {
  return {
    system: `HSK ${system}`,
    level: `Level ${level}`,
    evidenceKind: "standalone",
    note: `${character} is listed as a standalone character in HSK ${system} Level ${level}.`,
  };
}

function guide({ hsk20, hsk30, seoDescription, ...entry }: GuideSeed): StrokeOrderCharacter {
  return {
    ...entry,
    hsk: [...(hsk20 ? [hsk(entry.character, "2.0", hsk20)] : []), hsk(entry.character, "3.0", hsk30)],
    publicationStatus: "complete",
    seo: {
      title: `${entry.character} (${entry.pinyin}) Stroke Order, Meaning & Examples`,
      h1: `How to Write ${entry.character} (${entry.pinyin}): Stroke Order, Meaning & Examples`,
      description: seoDescription,
    },
  };
}

export const pilotStrokeOrderCharacters: StrokeOrderCharacter[] = [
  guide({
    character: "中", pinyin: "zhōng", meaning: "middle; centre", strokes: 4, radical: "丨", traditional: "中", structure: "Single-component", learningTier: "High-frequency", hsk30: "1",
    importance: "中 appears in country names, language names, and everyday position words, so its central line is worth learning early.",
    components: [{ character: "口", explanation: "The outer box stays balanced on either side of the centre." }, { character: "丨", explanation: "The final vertical passes through the box and extends below it." }],
    readingNotes: "Read 中 as zhōng with a level first tone in 中国 and 中间. The same character is zhòng in words such as 中奖.",
    useNotes: "Use 中 for a middle position in 中间, and as the first character of 中国 and 中文. These compounds have different meanings, so learn each whole word.",
    usageTitle: "Middle positions and Chinese language words",
    usage: "中 can point to a physical centre, but it also anchors familiar words for China and Chinese. Compare 中间 for a location with 中文 for a language; the second character completes the meaning rather than merely decorating 中.",
    writingTip: "Leave equal space on both sides of the central vertical, close the box before drawing that last line, and let the vertical finish just below the lower edge.",
    examples: [{ hanzi: "中国", pinyin: "Zhōngguó", meaning: "China" }, { hanzi: "中文", pinyin: "Zhōngwén", meaning: "Chinese language" }, { hanzi: "中间", pinyin: "zhōngjiān", meaning: "middle" }, { hanzi: "中午", pinyin: "zhōngwǔ", meaning: "noon" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我学中文。", pinyin: "Wǒ xué Zhōngwén.", meaning: "I study Chinese." }, { learningLabel: "Developing", hanzi: "书在桌子中间。", pinyin: "Shū zài zhuōzi zhōngjiān.", meaning: "The book is in the middle of the table." }, { learningLabel: "Stretch", hanzi: "中午我们在学校附近吃饭。", pinyin: "Zhōngwǔ wǒmen zài xuéxiào fùjìn chīfàn.", meaning: "At noon we eat near the school." }],
    commonMistake: "Do not stop the centre line inside the box or place it against one side; the line should divide the enclosure clearly and extend below it.",
    confusableCharacter: { character: "申", guidance: "中 has a simple box crossed by one vertical, while 申 extends that vertical through a different inner shape; check the enclosure before writing." },
    relatedCharacters: ["国", "书"], seoDescription: "Learn 中 (zhōng) stroke order, its centred vertical, meanings in 中国 and 中间, common words, example sentences, and printable writing practice.",
  }),
  guide({
    character: "国", pinyin: "guó", meaning: "country; nation", strokes: 8, radical: "囗", traditional: "國", structure: "Enclosure", learningTier: "Beginner", hsk30: "1",
    importance: "国 is the country character in 中国 and 国家, helping learners read place and nationality vocabulary.",
    components: [{ character: "囗", explanation: "The large outer enclosure surrounds the inner component." }, { character: "玉", explanation: "The inner form is 玉, with a small dot that distinguishes it from 王." }],
    readingNotes: "国 is read guó with a rising second tone. The traditional form 國 has a different inner structure but the same common pronunciation.",
    useNotes: "Combine 国 with 中 for China, 家 for country or state, and 外 for abroad. In country names, check the complete compound for the intended place.",
    usageTitle: "Countries, states, and places abroad",
    usage: "国 names a country or nation and appears in many geographic compounds. 中国 is a place name, 国家 is the general word for a country, and 国外 means outside one's country. The surrounding character changes the scope of the idea.",
    writingTip: "Build the outer enclosure first, leave enough room for 玉 and its dot, then close the bottom last so the inner form does not touch the frame.",
    examples: [{ hanzi: "中国", pinyin: "Zhōngguó", meaning: "China" }, { hanzi: "国家", pinyin: "guójiā", meaning: "country; state" }, { hanzi: "国外", pinyin: "guówài", meaning: "abroad" }, { hanzi: "国王", pinyin: "guówáng", meaning: "king" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "中国很大。", pinyin: "Zhōngguó hěn dà.", meaning: "China is large." }, { learningLabel: "Developing", hanzi: "她去过很多国家。", pinyin: "Tā qù guo hěn duō guójiā.", meaning: "She has visited many countries." }, { learningLabel: "Stretch", hanzi: "他在国外工作，却常和家人说中文。", pinyin: "Tā zài guówài gōngzuò, què cháng hé jiārén shuō Zhōngwén.", meaning: "He works abroad but often speaks Chinese with his family." }],
    commonMistake: "Do not omit the dot inside 玉 or close the bottom enclosure before finishing the inner strokes; both details change the shape and order of 国.",
    confusableCharacter: { character: "因", guidance: "国 contains 玉 inside 囗, whereas 因 contains 大; identify the inner shape before closing the outer enclosure." },
    relatedCharacters: ["中", "家"], seoDescription: "Write 国 (guó) in eight strokes, compare its enclosure with similar characters, and practise 中国, 国家, and other useful country words.",
  }),
  guide({
    character: "天", pinyin: "tiān", meaning: "sky; day", strokes: 4, radical: "大", traditional: "天", structure: "Single-component", learningTier: "Beginner", hsk30: "1",
    importance: "天 builds today, tomorrow, weather, and daily-frequency words that appear in basic schedules and conversation.",
    components: [{ character: "一", explanation: "The short upper horizontal stays clearly above the lower crossbar." }, { character: "大", explanation: "The lower 大 shape opens into balanced left and right falling strokes." }],
    readingNotes: "天 is tiān with a level first tone. It means sky on its own and becomes a day or time marker in compounds such as 今天.",
    useNotes: "Use 今天 and 明天 for calendar reference, 每天 for frequency, and 天气 for weather. The whole word tells whether 天 means a day or the sky.",
    usageTitle: "Days, weather, and the sky",
    usage: "天 moves between the visible sky and the passage of days. In 今天 and 明天 it marks when something happens; in 天气 it helps describe the weather. Pair it with a time word before using it in a sentence about a schedule.",
    writingTip: "Keep the first horizontal shorter than the second, draw the central downward movement through the lower line, and spread the last two strokes without flattening them.",
    examples: [{ hanzi: "今天", pinyin: "jīntiān", meaning: "today" }, { hanzi: "明天", pinyin: "míngtiān", meaning: "tomorrow" }, { hanzi: "天气", pinyin: "tiānqì", meaning: "weather" }, { hanzi: "每天", pinyin: "měitiān", meaning: "every day" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "今天很热。", pinyin: "Jīntiān hěn rè.", meaning: "It is hot today." }, { learningLabel: "Developing", hanzi: "明天我们去学校。", pinyin: "Míngtiān wǒmen qù xuéxiào.", meaning: "We are going to school tomorrow." }, { learningLabel: "Stretch", hanzi: "天气好的时候，她每天走路回家。", pinyin: "Tiānqì hǎo de shíhou, tā měitiān zǒulù huí jiā.", meaning: "When the weather is good, she walks home every day." }],
    commonMistake: "Do not make the top horizontal as long as the lower one or squeeze the two falling strokes together; otherwise 天 loses its open lower shape.",
    confusableCharacter: { character: "夫", guidance: "天 has two horizontal levels above the spreading strokes, while 夫 places the central stroke differently through its upper form." },
    relatedCharacters: ["年", "日"], seoDescription: "Follow the four strokes of 天 (tiān), distinguish its two horizontals, and learn 今天, 明天, 天气, and printable day-word practice.",
  }),
  guide({
    character: "他", pinyin: "tā", meaning: "he; him", strokes: 5, radical: "亻", traditional: "他", structure: "Left-right", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "他 is a core third-person pronoun used in introductions, stories, questions, and descriptions of another person.",
    components: [{ character: "亻", explanation: "The person radical stays narrow on the left." }, { character: "也", explanation: "The right component supplies the broad curved lower movement." }],
    readingNotes: "他 is read tā with a level first tone. Its pronunciation matches 她, so writing requires attention to the person shown by the left component.",
    useNotes: "Use 他 for a male person or when a male referent is intended; use 他们 for a group that includes men. Spoken tā alone does not distinguish 他 from 她.",
    usageTitle: "Referring to another person",
    usage: "他 names a third person in a sentence, often as subject or object. In speech it sounds like 她; in writing the left component tells the reader which pronoun was chosen. Add 们 only when speaking about a group, not a single person.",
    writingTip: "Keep 亻 slim with a clear gap before 也, then give the right-side curve room to extend without allowing it to collide with the radical.",
    examples: [{ hanzi: "他们", pinyin: "tāmen", meaning: "they; them" }, { hanzi: "他的", pinyin: "tā de", meaning: "his" }, { hanzi: "他家", pinyin: "tā jiā", meaning: "his home" }, { hanzi: "他自己", pinyin: "tā zìjǐ", meaning: "himself" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "他是学生。", pinyin: "Tā shì xuésheng.", meaning: "He is a student." }, { learningLabel: "Developing", hanzi: "他今天在家看书。", pinyin: "Tā jīntiān zài jiā kàn shū.", meaning: "He is reading at home today." }, { learningLabel: "Stretch", hanzi: "如果他明天有时间，我们就一起去。", pinyin: "Rúguǒ tā míngtiān yǒu shíjiān, wǒmen jiù yìqǐ qù.", meaning: "If he has time tomorrow, we will go together." }],
    commonMistake: "Do not replace the narrow left-side 亻 with 女 when writing about him, and do not let the right-side 也 swallow the gap between components.",
    confusableCharacter: { character: "她", guidance: "他 and 她 sound the same, but 他 begins with the person radical 亻 and 她 begins with the woman radical 女." },
    relatedCharacters: ["她", "们"], seoDescription: "Learn 他 (tā) stroke order, the 亻 and 也 components, how it differs from 她, common pronoun phrases, and printable writing practice.",
  }),
  guide({
    character: "她", pinyin: "tā", meaning: "she; her", strokes: 6, radical: "女", traditional: "她", structure: "Left-right", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "她 is the written third-person pronoun for a woman and appears in everyday accounts of family, friends, and classmates.",
    components: [{ character: "女", explanation: "The woman radical narrows on the left and keeps a rising last stroke." }, { character: "也", explanation: "The right side curves outward with room for its lower ending." }],
    readingNotes: "她 is pronounced tā, exactly like 他. The written radical, not the sound, communicates the distinction in ordinary text.",
    useNotes: "Use 她 for a female person and 她们 for a group of women or girls. Keep the written referent consistent across a passage.",
    usageTitle: "Writing about a woman or girl",
    usage: "她 functions as subject or object in the same sentence positions as 他. The distinction appears only on the page: 女 identifies the female referent, while both pronouns are pronounced tā. Check the surrounding story before choosing the written form.",
    writingTip: "Keep 女 compact and upright on the left, finish its rising stroke before 也, and leave enough room for the lower curve of the right component.",
    examples: [{ hanzi: "她们", pinyin: "tāmen", meaning: "they; them (women)" }, { hanzi: "她的", pinyin: "tā de", meaning: "her; hers" }, { hanzi: "她家", pinyin: "tā jiā", meaning: "her home" }, { hanzi: "她自己", pinyin: "tā zìjǐ", meaning: "herself" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "她是老师。", pinyin: "Tā shì lǎoshī.", meaning: "She is a teacher." }, { learningLabel: "Developing", hanzi: "她今天和朋友去学校。", pinyin: "Tā jīntiān hé péngyou qù xuéxiào.", meaning: "She is going to school with a friend today." }, { learningLabel: "Stretch", hanzi: "她说这本书很有意思，想借给我们。", pinyin: "Tā shuō zhè běn shū hěn yǒu yìsi, xiǎng jiè gěi wǒmen.", meaning: "She said this book is interesting and wants to lend it to us." }],
    commonMistake: "Do not write 亻 in place of 女 or make the lower 女 stroke horizontal; the rising left stroke keeps 她 distinct from 他.",
    confusableCharacter: { character: "他", guidance: "她 has 女 on the left and refers to a female person in writing; 他 has 亻, although both are pronounced tā." },
    relatedCharacters: ["他", "们"], seoDescription: "Practise 她 (tā) in six strokes, see why its 女 radical differs from 他, and use the pronoun in words and short sentences.",
  }),
  guide({
    character: "们", pinyin: "men", meaning: "plural marker for people", strokes: 5, radical: "亻", traditional: "們", structure: "Left-right", learningTier: "Beginner", hsk30: "1",
    importance: "们 turns person pronouns into groups, so it is essential for 我们, 你们, 他们, and 她们.",
    components: [{ character: "亻", explanation: "The left person radical marks the people-related function." }, { character: "门", explanation: "The simplified door shape fills the right side with a wide interior." }],
    readingNotes: "们 is usually an unstressed neutral-tone men after a pronoun. Do not give it a full first-tone reading in 我们 or 他们.",
    useNotes: "Attach 们 to personal pronouns for plural groups. Do not add it mechanically to every noun after a number; 三个人 already expresses three people.",
    usageTitle: "Making personal pronouns plural",
    usage: "们 belongs to a small family of frequent group pronouns. 我们 includes the speaker, 你们 addresses listeners, and 他们 or 她们 refers to others. Its job is grammatical, so read the whole pronoun rather than translate 们 on its own.",
    writingTip: "Make 亻 narrow and high, then open the right-side 门 enough for its inner space; keep the final vertical and hook inside the character's outer width.",
    examples: [{ hanzi: "我们", pinyin: "wǒmen", meaning: "we; us" }, { hanzi: "你们", pinyin: "nǐmen", meaning: "you (plural)" }, { hanzi: "他们", pinyin: "tāmen", meaning: "they; them" }, { hanzi: "她们", pinyin: "tāmen", meaning: "they; them (women)" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我们走吧。", pinyin: "Wǒmen zǒu ba.", meaning: "Let's go." }, { learningLabel: "Developing", hanzi: "你们今天有课吗？", pinyin: "Nǐmen jīntiān yǒu kè ma?", meaning: "Do you have class today?" }, { learningLabel: "Stretch", hanzi: "他们明天去中国，想先练习说中文。", pinyin: "Tāmen míngtiān qù Zhōngguó, xiǎng xiān liànxí shuō Zhōngwén.", meaning: "They are going to China tomorrow and want to practise speaking Chinese first." }],
    commonMistake: "Do not use 们 after a numbered noun just to mark plural, and do not collapse the right-side 门 into a closed box when writing the character.",
    confusableCharacter: { character: "门", guidance: "门 is the door character on its own; 们 adds a narrow 亻 on the left to mark people in plural pronouns." },
    relatedCharacters: ["我", "他"], seoDescription: "Write 们 (men) in five strokes, learn its neutral-tone role in 我们 and 他们, and practise four common plural pronouns.",
  }),
  guide({
    character: "日", pinyin: "rì", meaning: "sun; day; date", strokes: 4, radical: "日", traditional: "日", structure: "Single-component", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "日 connects dates, birthdays, formal words for today, and the visual sun component found inside many characters.",
    components: [{ character: "日", explanation: "A tall outer rectangle encloses one clear middle horizontal." }],
    readingNotes: "日 is rì with a falling fourth tone. In dates and compounds it keeps that reading, while everyday 'day' often appears as 天.",
    useNotes: "Use 日 in 日期, 生日, and written time expressions such as 今日. Use 天 for many ordinary spoken day-count expressions.",
    usageTitle: "Dates, birthdays, and written day words",
    usage: "日 can refer to the sun or a calendar day, but its common beginner role is inside date vocabulary. 生日 names a birthday and 日期 means a date; 今日 is more written than everyday 今天. Match the compound to the register of the sentence.",
    writingTip: "Draw a tall, narrow outer shape, keep the middle horizontal level and separated, and close the bottom last so 日 does not spread into a wide box.",
    examples: [{ hanzi: "生日", pinyin: "shēngrì", meaning: "birthday" }, { hanzi: "日期", pinyin: "rìqī", meaning: "date" }, { hanzi: "日子", pinyin: "rìzi", meaning: "days; life" }, { hanzi: "今日", pinyin: "jīnrì", meaning: "today (written)" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "今天是我的生日。", pinyin: "Jīntiān shì wǒ de shēngrì.", meaning: "Today is my birthday." }, { learningLabel: "Developing", hanzi: "请在纸上写下日期。", pinyin: "Qǐng zài zhǐ shàng xiě xià rìqī.", meaning: "Please write the date on the paper." }, { learningLabel: "Stretch", hanzi: "虽然那段日子很忙，我们还是每天见面。", pinyin: "Suīrán nà duàn rìzi hěn máng, wǒmen háishi měitiān jiànmiàn.", meaning: "Although those days were busy, we still met every day." }],
    commonMistake: "Do not add a second inner line as in 目 or make the enclosure too square; 日 has one inner horizontal and a relatively tall shape.",
    confusableCharacter: { character: "目", guidance: "日 contains one horizontal inside its frame, while 目 contains two; count the inner lines before writing." },
    relatedCharacters: ["月", "天"], seoDescription: "See the four strokes of 日 (rì), distinguish it from 目, and learn date words such as 生日, 日期, and 今日.",
  }),
  guide({
    character: "月", pinyin: "yuè", meaning: "moon; month", strokes: 4, radical: "月", traditional: "月", structure: "Single-component", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "月 makes month names and calendar phrases while also naming the moon, so it is useful in time and nature vocabulary.",
    components: [{ character: "月", explanation: "The tall frame holds two short inner horizontals without closing into a square." }],
    readingNotes: "月 is yuè with a falling fourth tone. It follows a number in calendar months, such as 三月 for March.",
    useNotes: "Place a number before 月 to name a month, use 这个月 for the current month, and 月亮 for the moon in the sky.",
    usageTitle: "Months on the calendar and the moon",
    usage: "月 has two concrete uses: the visible moon and a calendar month. 一月 names January, while 一个月 means one month in duration. The added 个 changes the expression, so keep dates and durations separate when reading.",
    writingTip: "Make the outside tall, keep the two inner horizontals short and evenly spaced, and leave the lower frame open enough that it does not look like 日.",
    examples: [{ hanzi: "月亮", pinyin: "yuèliang", meaning: "moon" }, { hanzi: "每月", pinyin: "měiyuè", meaning: "every month" }, { hanzi: "这个月", pinyin: "zhège yuè", meaning: "this month" }, { hanzi: "月份", pinyin: "yuèfèn", meaning: "month" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "这个月很忙。", pinyin: "Zhège yuè hěn máng.", meaning: "This month is busy." }, { learningLabel: "Developing", hanzi: "天上的月亮很亮。", pinyin: "Tiān shàng de yuèliang hěn liàng.", meaning: "The moon in the sky is bright." }, { learningLabel: "Stretch", hanzi: "每个月我们都会选一天一起吃饭。", pinyin: "Měi ge yuè wǒmen dōu huì xuǎn yì tiān yìqǐ chīfàn.", meaning: "Every month we choose a day to eat together." }],
    commonMistake: "Do not close the lower frame into a box or omit one of the two inner horizontals; both details help keep 月 distinct from 日.",
    confusableCharacter: { character: "日", guidance: "月 has two short inner strokes in a more open tall frame, while 日 has one inner horizontal within a closed rectangle." },
    relatedCharacters: ["日", "年"], seoDescription: "Learn 月 (yuè) stroke order, compare its open frame with 日, and practise month and moon vocabulary on a printable worksheet.",
  }),
  guide({
    character: "个", pinyin: "gè", meaning: "general measure word; individual", strokes: 3, radical: "人", traditional: "個", structure: "Top-bottom", learningTier: "High-frequency", hsk20: "1", hsk30: "1",
    importance: "个 is the most common general measure word and also appears in everyday pointing words such as 这个 and 那个.",
    components: [{ character: "人", explanation: "The upper 人 opens symmetrically over the vertical." }, { character: "丨", explanation: "The final vertical descends from the centre of the upper shape." }],
    readingNotes: "个 is gè with a falling fourth tone, though it may sound lighter in fast speech inside 这个 and 那个.",
    useNotes: "Put 个 between a number or pointing word and a noun when it is the appropriate measure word. It is common, but many nouns have a more specific measure word.",
    usageTitle: "Counting people and pointing to things",
    usage: "个 can count a person in 一个人 or connect a demonstrative to a noun in 这个人. It does not replace every measure word: 一本书 uses 本. Learn the noun together with its natural measure word rather than applying 个 universally.",
    writingTip: "Open the two top strokes like 人, then drop the final vertical straight through their centre; keep the line long enough without turning the shape into a cross.",
    examples: [{ hanzi: "一个", pinyin: "yí ge", meaning: "one (general measure)" }, { hanzi: "这个", pinyin: "zhège", meaning: "this one" }, { hanzi: "那个", pinyin: "nàge", meaning: "that one" }, { hanzi: "个人", pinyin: "gèrén", meaning: "individual; personal" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我有一个苹果。", pinyin: "Wǒ yǒu yí ge píngguǒ.", meaning: "I have an apple." }, { learningLabel: "Developing", hanzi: "这个人是我的老师。", pinyin: "Zhège rén shì wǒ de lǎoshī.", meaning: "This person is my teacher." }, { learningLabel: "Stretch", hanzi: "我们班有三个人想学写这个字。", pinyin: "Wǒmen bān yǒu sān ge rén xiǎng xué xiě zhège zì.", meaning: "Three people in our class want to learn to write this character." }],
    commonMistake: "Do not add a lower horizontal to 个 or use it for every noun without checking the appropriate measure word; both form and grammar matter.",
    confusableCharacter: { character: "介", guidance: "个 finishes with a single central vertical; 介 adds a second descending stroke below the opening 人." },
    relatedCharacters: ["这", "那"], seoDescription: "Write 个 (gè) in three strokes and learn when to use it in 一个, 这个, and 那个, with examples and printable practice.",
  }),
  guide({
    character: "和", pinyin: "hé", meaning: "and; with; harmony", strokes: 8, radical: "禾", traditional: "和", structure: "Left-right", learningTier: "High-frequency", hsk20: "1", hsk30: "1",
    importance: "和 joins people and nouns in basic sentences and also forms common words about peace and getting along.",
    components: [{ character: "禾", explanation: "The grain component stays narrow on the left." }, { character: "口", explanation: "A compact mouth square balances the wider lower left strokes." }],
    readingNotes: "和 is normally hé when it means 'and' or 'with'. It has other readings in specific words, so check the complete word before pronouncing it.",
    useNotes: "Use 和 to connect nouns or people, such as 我和你. It does not replace every English 'and' between two full clauses.",
    usageTitle: "Joining people and related ideas",
    usage: "和 links two people, objects, or ideas within one phrase. 我和你 can be a sentence subject; 和平 names peace. When English 'and' joins two independent actions, Chinese may use a different sentence structure instead of inserting 和.",
    writingTip: "Keep 禾 narrow and let its lower strokes slope away from the centre, then place 口 at mid-height on the right without stretching it into a large box.",
    examples: [{ hanzi: "我和你", pinyin: "wǒ hé nǐ", meaning: "you and I" }, { hanzi: "和平", pinyin: "hépíng", meaning: "peace" }, { hanzi: "和好", pinyin: "héhǎo", meaning: "make up; reconcile" }, { hanzi: "和气", pinyin: "héqi", meaning: "friendly; harmonious" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我和你一起去。", pinyin: "Wǒ hé nǐ yìqǐ qù.", meaning: "You and I will go together." }, { learningLabel: "Developing", hanzi: "她和朋友在家看书。", pinyin: "Tā hé péngyou zài jiā kàn shū.", meaning: "She is reading at home with a friend." }, { learningLabel: "Stretch", hanzi: "他们昨天和好了，今天又一起吃饭。", pinyin: "Tāmen zuótiān héhǎo le, jīntiān yòu yìqǐ chīfàn.", meaning: "They made up yesterday and ate together again today." }],
    commonMistake: "Do not write 禾 at full width or enlarge 口 until it covers the right half; the left grain shape and compact mouth need separate space.",
    confusableCharacter: { character: "种", guidance: "和 and 种 both begin with 禾, but 和 ends in 口 while 种 uses 中 on the right." },
    relatedCharacters: ["我", "你"], seoDescription: "Learn 和 (hé) stroke order, see its 禾 and 口 components, and use it for 'and', 'with', 和平, and printable practice.",
  }),
  guide({
    character: "多", pinyin: "duō", meaning: "many; much", strokes: 6, radical: "夕", traditional: "多", structure: "Top-bottom", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "多 helps learners ask how many, describe quantity, and compare amounts in ordinary shopping and classroom situations.",
    components: [{ character: "夕", explanation: "The upper 夕 stays compact and slightly offset." }, { character: "夕", explanation: "The lower 夕 spreads more widely to support the stacked shape." }],
    readingNotes: "多 is duō with a level first tone. In 多少, the following 少 is often light, so hear the two-character question as one unit.",
    useNotes: "Use 很多 for a large amount, 多少 to ask quantity, and 多大 to ask size or age in context. The question word changes with the noun.",
    usageTitle: "Quantity, degree, and how much",
    usage: "多 describes an amount greater than expected or asks about quantity when paired with another character. 多少 asks how many or how much, 多大 asks about size or age, and 多久 asks duration. Reading the second character prevents treating all three questions alike.",
    writingTip: "Stack two 夕 forms with the upper one smaller and slightly higher; leave a clear gap between them and let the lower strokes widen for balance.",
    examples: [{ hanzi: "多少", pinyin: "duōshao", meaning: "how many; how much" }, { hanzi: "很多", pinyin: "hěn duō", meaning: "many; much" }, { hanzi: "多大", pinyin: "duō dà", meaning: "how big; how old" }, { hanzi: "多久", pinyin: "duōjiǔ", meaning: "how long" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "这里有很多书。", pinyin: "Zhèlǐ yǒu hěn duō shū.", meaning: "There are many books here." }, { learningLabel: "Developing", hanzi: "你每天花多少时间学中文？", pinyin: "Nǐ měitiān huā duōshao shíjiān xué Zhōngwén?", meaning: "How much time do you spend studying Chinese each day?" }, { learningLabel: "Stretch", hanzi: "虽然他认识很多字，写字的时候还是会先看笔顺。", pinyin: "Suīrán tā rènshi hěn duō zì, xiě zì de shíhou háishi huì xiān kàn bǐshùn.", meaning: "Although he knows many characters, he still checks stroke order before writing." }],
    commonMistake: "Do not merge the two 夕 shapes into one tangled group or make the upper form larger than the lower one; 多 needs visible stacked rhythm.",
    confusableCharacter: { character: "夕", guidance: "夕 is one compact evening shape, while 多 stacks two similar forms and uses a wider lower half." },
    relatedCharacters: ["小", "大"], seoDescription: "Follow 多 (duō) stroke order, see its two stacked 夕 shapes, and use 多少, 多大, and 多久 in real sentences.",
  }),
  guide({
    character: "这", pinyin: "zhè", meaning: "this", strokes: 7, radical: "辶", traditional: "這", structure: "Enclosing", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "这 points to a nearby person, object, or situation and forms some of the first phrases a learner says.",
    components: [{ character: "文", explanation: "The inner 文 is written before the surrounding movement radical." }, { character: "辶", explanation: "The walking radical wraps below and to the left of 文." }],
    readingNotes: "这 is zhè with a falling fourth tone. In 这个, the following 个 can be lighter in connected speech.",
    useNotes: "Use 这 with a measure word before a noun, as in 这本书; 这里 points to a place, while 这样 describes a way of doing something.",
    usageTitle: "Pointing to something nearby",
    usage: "这 identifies a nearby or current person, thing, or idea. 这个 is a general pointing phrase, 这里 refers to a place, and 这样 refers to a manner. Before many nouns, add the appropriate measure word rather than placing 这 directly beside the noun.",
    writingTip: "Finish the compact 文 first, then draw the 辶 strokes around its left and lower edges; leave a clear open space before the long finishing sweep.",
    examples: [{ hanzi: "这个", pinyin: "zhège", meaning: "this one" }, { hanzi: "这里", pinyin: "zhèlǐ", meaning: "here" }, { hanzi: "这些", pinyin: "zhèxiē", meaning: "these" }, { hanzi: "这样", pinyin: "zhèyàng", meaning: "like this" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "这是什么？", pinyin: "Zhè shì shénme?", meaning: "What is this?" }, { learningLabel: "Developing", hanzi: "这本书是我的。", pinyin: "Zhè běn shū shì wǒ de.", meaning: "This book is mine." }, { learningLabel: "Stretch", hanzi: "如果你这样写这个字，最后一笔会更平稳。", pinyin: "Rúguǒ nǐ zhèyàng xiě zhège zì, zuìhòu yì bǐ huì gèng píngwěn.", meaning: "If you write this character this way, the final stroke will be steadier." }],
    commonMistake: "Do not draw the long 辶 sweep before completing 文 or close the space between them; the movement radical finishes around the inner form.",
    confusableCharacter: { character: "那", guidance: "这 points to a nearby or current referent and begins with 文 plus 辶; 那 points farther away and has a different right-side 阝." },
    relatedCharacters: ["那", "个"], seoDescription: "Learn 这 (zhè) stroke order, write 文 before 辶, and practise 这个, 这里, and other useful pointing phrases.",
  }),
  guide({
    character: "那", pinyin: "nà", meaning: "that; those", strokes: 6, radical: "阝", traditional: "那", structure: "Left-right", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "那 lets a speaker point to a person, thing, or place away from the current focus and contrasts naturally with 这.",
    components: [{ character: "那", explanation: "The left form keeps its horizontal layers compact." }, { character: "阝", explanation: "The right-side place radical descends without crowding the left." }],
    readingNotes: "那 is usually nà with a falling fourth tone for 'that'. Some fixed expressions have other readings, so keep the common demonstrative meaning in focus here.",
    useNotes: "Use 那个 before a noun when 个 is the right measure word, 那里 for a place, and 那些 for plural 'those'. Contrast each with 这, 这里, and 这些.",
    usageTitle: "Pointing away from the current focus",
    usage: "那 refers to something farther away, previously mentioned, or outside the immediate focus. 那个 points to a particular item, 那里 points to a place, and 那些 refers to several items. The contrast with 这 helps a listener follow what is being selected.",
    writingTip: "Build the compact left side with clear horizontal spacing, then add the right-side 阝 as a separate vertical shape; keep its lower ending from folding under the left.",
    examples: [{ hanzi: "那个", pinyin: "nàge", meaning: "that one" }, { hanzi: "那里", pinyin: "nàlǐ", meaning: "there" }, { hanzi: "那些", pinyin: "nàxiē", meaning: "those" }, { hanzi: "那么", pinyin: "nàme", meaning: "then; in that way" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "那是我的书。", pinyin: "Nà shì wǒ de shū.", meaning: "That is my book." }, { learningLabel: "Developing", hanzi: "那个人在学校门口等你。", pinyin: "Nàge rén zài xuéxiào ménkǒu děng nǐ.", meaning: "That person is waiting for you at the school entrance." }, { learningLabel: "Stretch", hanzi: "那些孩子已经走了，我们明天再去那里。", pinyin: "Nàxiē háizi yǐjīng zǒu le, wǒmen míngtiān zài qù nàlǐ.", meaning: "Those children have left; we will go there again tomorrow." }],
    commonMistake: "Do not attach the right-side 阝 to the left horizontals as one solid block, and do not confuse the distant 那 with nearby 这 in example sentences.",
    confusableCharacter: { character: "这", guidance: "那 uses a right-side 阝 and often means 'that'; 这 uses 辶 around 文 and usually means 'this'." },
    relatedCharacters: ["这", "个"], seoDescription: "Write 那 (nà) in six strokes, compare it with 这, and use 那个, 那里, and 那些 in everyday sentences.",
  }),
  guide({
    character: "谁", pinyin: "shéi", meaning: "who; whom", strokes: 10, radical: "讠", traditional: "誰", structure: "Left-right", learningTier: "Beginner", hsk20: "1", hsk30: "1",
    importance: "谁 is the question word for identifying people, making it useful in introductions, calls, and everyday classroom talk.",
    components: [{ character: "讠", explanation: "The simplified speech radical stays narrow on the left." }, { character: "隹", explanation: "The right component is tall with several separated horizontal strokes." }],
    readingNotes: "谁 is commonly pronounced shéi; shuí is also heard in standard Mandarin. The meaning stays 'who' in ordinary questions.",
    useNotes: "Place 谁 where the person being asked about would appear: 谁来了 asks for a subject, while 你找谁 asks for an object.",
    usageTitle: "Asking which person",
    usage: "谁 asks for a person's identity and can occupy different sentence positions. 谁来了 asks who came; 你认识谁 asks whom you know. Keep the rest of the sentence in its normal order rather than automatically moving 谁 to the front as English often does.",
    writingTip: "Write a slim 讠 first, then give 隹 enough width for its stacked horizontals; keep the vertical line straight so the right side does not become a dense block.",
    examples: [{ hanzi: "谁的", pinyin: "shéi de", meaning: "whose" }, { hanzi: "谁来", pinyin: "shéi lái", meaning: "who is coming" }, { hanzi: "谁知道", pinyin: "shéi zhīdào", meaning: "who knows" }, { hanzi: "是谁", pinyin: "shì shéi", meaning: "who is it" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "他是谁？", pinyin: "Tā shì shéi?", meaning: "Who is he?" }, { learningLabel: "Developing", hanzi: "这本书是谁的？", pinyin: "Zhè běn shū shì shéi de?", meaning: "Whose book is this?" }, { learningLabel: "Stretch", hanzi: "你知道明天是谁来教我们写字吗？", pinyin: "Nǐ zhīdào míngtiān shì shéi lái jiāo wǒmen xiě zì ma?", meaning: "Do you know who is coming to teach us writing tomorrow?" }],
    commonMistake: "Do not widen the left 讠 until it crowds 隹 or omit one of the right-side horizontals; 谁 needs a clear narrow-left, tall-right structure.",
    confusableCharacter: { character: "难", guidance: "谁 has the speech radical 讠 on the left, while 难 has 又; both share the tall right-side 隹 component." },
    relatedCharacters: ["他", "她"], seoDescription: "Follow 谁 (shéi) stroke order, distinguish 讠 from similar left components, and ask natural 'who' questions with examples.",
  }),
  guide({
    character: "也", pinyin: "yě", meaning: "also; too", strokes: 3, radical: "乙", traditional: "也", structure: "Single-component", learningTier: "High-frequency", hsk20: "2", hsk30: "1",
    importance: "也 lets a learner add a matching fact to a conversation and appears in many short responses about people and actions.",
    components: [{ character: "也", explanation: "Three strokes create a wide upper movement and a hooked lower finish." }],
    readingNotes: "也 is yě with a third tone. In quick speech the tone may be shortened before another third tone, but its dictionary reading stays yě.",
    useNotes: "Place 也 before the verb or adjective being shared: 我也去 means 'I am going too'. Do not place it after the whole clause as English often places 'too'.",
    usageTitle: "Adding a matching fact",
    usage: "也 links a new statement to an earlier one: if someone studies Chinese, 我也学中文 adds that the speaker does too. It usually comes after the subject and before the verb or adjective, so word order is the key to using it naturally.",
    writingTip: "Keep the upper two movements open, then give the final hooked stroke a rounded turn and enough room to extend without closing the whole character into a box.",
    examples: [{ hanzi: "也是", pinyin: "yě shì", meaning: "also is" }, { hanzi: "也有", pinyin: "yě yǒu", meaning: "also has" }, { hanzi: "也好", pinyin: "yě hǎo", meaning: "also good; either is fine" }, { hanzi: "也许", pinyin: "yěxǔ", meaning: "perhaps" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我也去。", pinyin: "Wǒ yě qù.", meaning: "I am going too." }, { learningLabel: "Developing", hanzi: "她也在学中文。", pinyin: "Tā yě zài xué Zhōngwén.", meaning: "She is also studying Chinese." }, { learningLabel: "Stretch", hanzi: "如果你今天没有时间，明天来也可以。", pinyin: "Rúguǒ nǐ jīntiān méiyǒu shíjiān, míngtiān lái yě kěyǐ.", meaning: "If you have no time today, coming tomorrow is also fine." }],
    commonMistake: "Do not put 也 after the completed sentence just because English 'too' can appear at the end; in Chinese it normally precedes the shared predicate.",
    confusableCharacter: { character: "他", guidance: "也 is a character on its own; 他 adds 亻 on the left to form the pronoun 'he', so check for the extra person radical." },
    relatedCharacters: ["他", "是"], seoDescription: "Learn the three strokes of 也 (yě), place 'also' before a verb, and practise short natural sentences and writing grids.",
  }),
];
