import type { StrokeOrderCharacter, StrokeOrderHskCard } from "./stroke-order-characters";

function hsk(system: "2.0" | "3.0", level: "1" | "2" | "3", character: string): StrokeOrderHskCard {
  return {
    system: `HSK ${system}`,
    level: `Level ${level}`,
    evidenceKind: "standalone",
    note: `Exact standalone ${character} record in the local HSK ${system} Level ${level} catalogue.`,
  };
}

type GuideInput = Omit<StrokeOrderCharacter, "publicationStatus" | "seo"> & {
  seoDescription: string;
};

function guide(input: GuideInput): StrokeOrderCharacter {
  const { seoDescription, ...entry } = input;
  return {
    ...entry,
    publicationStatus: "complete",
    seo: {
      title: `${entry.character} Stroke Order, Meaning & Words (${entry.pinyin})`,
      h1: `How to write ${entry.character} (${entry.pinyin}) in Chinese`,
      description: seoDescription,
    },
  };
}

export const expandedStrokeOrderCharacters: StrokeOrderCharacter[] = [
  guide({
    character: "好", pinyin: "hǎo", meaning: "good; well", strokes: 6, radical: "女", traditional: "好", structure: "Left-right", learningTier: "High-frequency",
    hsk: [hsk("2.0", "1", "好"), hsk("3.0", "1", "好")],
    importance: "好 anchors greetings, evaluations, agreement, and result complements, so it appears from a learner's first conversation onward.",
    components: [{ character: "女", explanation: "The left-side woman component narrows and its final horizontal becomes a rising stroke." }, { character: "子", explanation: "The child component sits slightly wider on the right and supplies the finishing horizontal." }],
    readingNotes: "好 is usually hǎo, a third tone. In the verb 好奇 it is also hǎo, while the less common hào reading appears in 好学 and 爱好.",
    useNotes: "Use 很好 for an evaluation, 你好 as a greeting, and 好了 to signal that something is ready or settled. 好 can also introduce a proposed action: 好，我们走吧。",
    usageTitle: "Greeting, quality, and readiness",
    usage: "好 moves between adjective, result, and conversational signal. It can describe quality, confirm that a task is finished, soften agreement, or combine with another character to express a preference. Read the sentence role before translating it as only ‘good’.",
    writingTip: "Keep 女 compact on the left with a rising final stroke; centre 子 on the right and let its last horizontal support the whole character without crossing back into 女.",
    examples: [{ hanzi: "你好", pinyin: "nǐ hǎo", meaning: "hello" }, { hanzi: "很好", pinyin: "hěn hǎo", meaning: "very good" }, { hanzi: "好吃", pinyin: "hǎochī", meaning: "tasty" }, { hanzi: "爱好", pinyin: "àihào", meaning: "hobby; interest" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "你好！", pinyin: "Nǐ hǎo!", meaning: "Hello!" }, { learningLabel: "Developing", hanzi: "这个菜很好吃。", pinyin: "Zhège cài hěn hǎochī.", meaning: "This dish is delicious." }, { learningLabel: "Stretch", hanzi: "作业写好以后，我们再出去。", pinyin: "Zuòyè xiě hǎo yǐhòu, wǒmen zài chūqù.", meaning: "After the homework is finished, we will go out." }],
    commonMistake: "Do not write 女 at full width or leave 子 floating above it; the two sides should share one baseline and a narrow central gap.",
    confusableCharacter: { character: "妈", guidance: "好 has 子 on the right, while 妈 has 马; check the right component before using either familiar left-side 女 form." },
    relatedCharacters: ["坏", "你", "吃"],
    seoDescription: "Learn 好 (hǎo): six-stroke order, 女 and 子 components, third-tone usage, 好 vs 坏, common words, graded sentences, and printable practice.",
  }),
  guide({
    character: "不", pinyin: "bù", meaning: "not; no", strokes: 4, radical: "一", traditional: "不", structure: "Single-component", learningTier: "High-frequency",
    hsk: [hsk("2.0", "1", "不"), hsk("3.0", "1", "不")],
    importance: "不 is the default negator for habits, descriptions, intentions, and many present or future statements in everyday Mandarin.",
    components: [{ character: "不", explanation: "A top horizontal controls the centred vertical, left-falling stroke, and right-side dot." }],
    readingNotes: "The dictionary tone is bù. Before another fourth tone it is normally pronounced bú, as in 不是 bú shì, although Pinyin spelling often keeps bù.",
    useNotes: "Put 不 before a verb or adjective for general, habitual, or intended negation. Completed non-occurrence and possession usually call for 没 instead.",
    usageTitle: "General and habitual negation",
    usage: "不 rejects a description, habit, plan, or judgment: 不大, 不去, or 不好. It is not interchangeable with 没, which commonly denies that an event happened or that someone possesses something. Time reference decides which negative word fits.",
    writingTip: "Draw a steady top horizontal, drop the central vertical through its middle, then balance the left fall against the shorter right dot without turning the form into 木.",
    examples: [{ hanzi: "不是", pinyin: "bú shì", meaning: "is not" }, { hanzi: "不好", pinyin: "bù hǎo", meaning: "not good" }, { hanzi: "不用", pinyin: "bú yòng", meaning: "need not" }, { hanzi: "不来", pinyin: "bù lái", meaning: "not come" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我不是老师。", pinyin: "Wǒ bú shì lǎoshī.", meaning: "I am not a teacher." }, { learningLabel: "Developing", hanzi: "他今天不来。", pinyin: "Tā jīntiān bù lái.", meaning: "He is not coming today." }, { learningLabel: "Stretch", hanzi: "我不喝咖啡，但是我喝茶。", pinyin: "Wǒ bù hē kāfēi, dànshì wǒ hē chá.", meaning: "I do not drink coffee, but I drink tea." }],
    commonMistake: "Do not add a second lower branch as if writing 木; 不 ends with a separate right dot and retains an open lower centre.",
    confusableCharacter: { character: "没", guidance: "不 negates habits, descriptions, and intentions; 没 usually denies possession or a completed event, so the choice is grammatical rather than visual." },
    relatedCharacters: ["没", "是", "好"],
    seoDescription: "Study 不 (bù/bú) with its four strokes, tone change before fourth tones, the 不 vs 没 decision, reusable negatives, and custom handwriting practice.",
  }),
  guide({
    character: "没", pinyin: "méi", meaning: "not have; did not", strokes: 7, radical: "氵", traditional: "沒", structure: "Left-right", learningTier: "High-frequency",
    hsk: [hsk("2.0", "1", "没"), hsk("3.0", "1", "没")],
    importance: "没 is essential for denying possession and reporting that an expected or completed action did not happen.",
    components: [{ character: "氵", explanation: "Three water dots descend on the narrow left side." }, { character: "殳", explanation: "The simplified right shape uses a compact upper turn and the lower 又-like movement." }],
    readingNotes: "Read 没 as méi in 没有 and ordinary negation. The reading mò appears in words about sinking or submerging, such as 淹没.",
    useNotes: "Use 没有 for ‘do not have’ and 没 before a verb for an action that did not occur. Do not use 不有 as the ordinary opposite of 有.",
    usageTitle: "Missing possession or past occurrence",
    usage: "没 looks backward at an event that did not happen and also forms 没有 for absence or non-possession. It pairs naturally with time expressions such as 昨天 and 还, while 不 more often covers routines, descriptions, and intentions.",
    writingTip: "Space the three water dots vertically, keep the right side wider, and preserve the turning separation between its upper and lower parts instead of compressing them into one knot.",
    examples: [{ hanzi: "没有", pinyin: "méiyǒu", meaning: "not have; there is not" }, { hanzi: "没来", pinyin: "méi lái", meaning: "did not come" }, { hanzi: "没事", pinyin: "méishì", meaning: "it is okay; nothing is wrong" }, { hanzi: "还没", pinyin: "hái méi", meaning: "not yet" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我没有书。", pinyin: "Wǒ méiyǒu shū.", meaning: "I do not have a book." }, { learningLabel: "Developing", hanzi: "他昨天没来。", pinyin: "Tā zuótiān méi lái.", meaning: "He did not come yesterday." }, { learningLabel: "Stretch", hanzi: "作业还没写好，我不能出去。", pinyin: "Zuòyè hái méi xiě hǎo, wǒ bù néng chūqù.", meaning: "The homework is not finished yet, so I cannot go out." }],
    commonMistake: "Do not join the three left dots into a vertical line or replace the lower right turn with another water dot; each side has a different job.",
    confusableCharacter: { character: "不", guidance: "没 handles non-possession and unrealized past events, whereas 不 usually negates a state, habit, judgment, or intended action." },
    relatedCharacters: ["不", "有", "来"],
    seoDescription: "Learn 没 (méi): seven-stroke construction, 没有 and past-event negation, contrast with 不, example phrases, and printable Chinese writing grids.",
  }),
  guide({
    character: "有", pinyin: "yǒu", meaning: "to have; there is", strokes: 6, radical: "月", traditional: "有", structure: "Top-bottom", learningTier: "High-frequency",
    hsk: [hsk("2.0", "1", "有"), hsk("3.0", "1", "有")],
    importance: "有 expresses possession and existence, two sentence patterns learners use for family, objects, places, and schedules.",
    components: [{ character: "𠂇", explanation: "The top horizontal and left fall create a protective overhang." }, { character: "月", explanation: "The lower 月 stays centred with two clear inner horizontals." }],
    readingNotes: "有 is yǒu with a third tone. In fast speech, the full third-tone dip may be reduced, but the lexical tone remains third.",
    useNotes: "Use subject + 有 + object for possession and place + 有 + noun for existence. Negate both with 没有, not with 不有.",
    usageTitle: "Possession and existence",
    usage: "有 links an owner to something possessed, or a location to something that exists there. Compare 我有一本书 with 桌上有一本书: the word stays the same, but the opening phrase tells whether the sentence is about ownership or presence.",
    writingTip: "Extend the top left-falling stroke just enough to cover 月, keep 月 upright beneath it, and leave both inner lines visible rather than filling the lower box.",
    examples: [{ hanzi: "没有", pinyin: "méiyǒu", meaning: "not have" }, { hanzi: "有人", pinyin: "yǒurén", meaning: "someone; occupied" }, { hanzi: "有名", pinyin: "yǒumíng", meaning: "famous" }, { hanzi: "有用", pinyin: "yǒuyòng", meaning: "useful" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我有一本书。", pinyin: "Wǒ yǒu yì běn shū.", meaning: "I have a book." }, { learningLabel: "Developing", hanzi: "桌上有一杯水。", pinyin: "Zhuō shàng yǒu yì bēi shuǐ.", meaning: "There is a glass of water on the table." }, { learningLabel: "Stretch", hanzi: "今天下午我有时间，可以来帮你。", pinyin: "Jīntiān xiàwǔ wǒ yǒu shíjiān, kěyǐ lái bāng nǐ.", meaning: "I have time this afternoon and can come help you." }],
    commonMistake: "Do not let the upper slant cut through 月 or write the lower component as 日; 月 keeps a slightly different inner spacing and shape.",
    confusableCharacter: { character: "没", guidance: "有 states possession or existence, and its ordinary negative is 没有; pairing the two prevents the common but incorrect form 不有." },
    relatedCharacters: ["没", "一", "人"],
    seoDescription: "Understand 有 (yǒu) for possession and existence with six-stroke guidance, 没有 negation, sentence patterns, vocabulary, and worksheet practice.",
  }),
  guide({
    character: "上", pinyin: "shàng", meaning: "up; above; on; previous", strokes: 3, radical: "一", traditional: "上", structure: "Single-component", learningTier: "High-frequency",
    hsk: [hsk("2.0", "1", "上"), hsk("3.0", "1", "上")],
    importance: "上 connects spatial position, movement upward, time reference, attendance, and starting an activity in compact everyday patterns.",
    components: [{ character: "上", explanation: "A central vertical and short upper mark sit above the long grounding horizontal." }],
    readingNotes: "上 is usually shàng with a falling tone. In directional and compound use, meaning comes from its partner: 上来, 上课, or 上个月.",
    useNotes: "Use noun + 上 for ‘on’ a surface, 上 + noun for attending or starting, and 上个 for the previous unit of time. Directional 上来 adds motion toward a reference point.",
    usageTitle: "Position, movement, and earlier time",
    usage: "上 can locate something above or on a surface, send movement upward, mark attendance in 上课, and point backward in time in 上周. Its position relative to the noun is meaningful, so learn each sentence frame rather than one English equivalent.",
    writingTip: "Place the vertical near the centre, add the short upper horizontal on its left side, and finish with a longer baseline that clearly puts the marks above it.",
    examples: [{ hanzi: "上面", pinyin: "shàngmiàn", meaning: "above; on top" }, { hanzi: "上课", pinyin: "shàngkè", meaning: "attend class" }, { hanzi: "上来", pinyin: "shànglái", meaning: "come up" }, { hanzi: "上午", pinyin: "shàngwǔ", meaning: "morning" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "书在桌上。", pinyin: "Shū zài zhuō shàng.", meaning: "The book is on the table." }, { learningLabel: "Developing", hanzi: "我们九点上课。", pinyin: "Wǒmen jiǔ diǎn shàngkè.", meaning: "Our class starts at nine." }, { learningLabel: "Stretch", hanzi: "请上来把答案写在黑板上。", pinyin: "Qǐng shànglái bǎ dá'àn xiě zài hēibǎn shàng.", meaning: "Please come up and write the answer on the board." }],
    commonMistake: "Do not place the short upper mark below the long horizontal; the visual relationship of the marks above the baseline carries the character's shape.",
    confusableCharacter: { character: "下", guidance: "上 places the short mark above its long reference line, while 下 places the extra mark and descending stroke below that line." },
    relatedCharacters: ["下", "在", "来"],
    seoDescription: "Write 上 (shàng) in three strokes and learn its location, movement, class, and time patterns through contrasts with 下, examples, and grid practice.",
  }),
  guide({
    character: "下", pinyin: "xià", meaning: "down; below; under; next", strokes: 3, radical: "一", traditional: "下", structure: "Single-component", learningTier: "High-frequency",
    hsk: [hsk("2.0", "1", "下"), hsk("3.0", "1", "下")],
    importance: "下 organizes lower position, downward motion, leaving a vehicle, finishing class, and the next period of time.",
    components: [{ character: "下", explanation: "The long top horizontal acts as a reference line, with the vertical and dot falling below it." }],
    readingNotes: "下 is xià with a falling tone. The same reading links spatial, directional, and time expressions such as 下面, 下去, and 下周.",
    useNotes: "Use noun + 下 for underneath, 下 + vehicle for getting off, 下课 for class ending, and 下个 for the following unit. 下来 moves down toward a reference point.",
    usageTitle: "Lower space, downward action, and next time",
    usage: "下 places something beneath a reference, describes movement downward, marks the end of scheduled activities, and points forward in time. Compare 下课 with 上课 and 下个月 with 上个月 to see how one spatial contrast extends into routines.",
    writingTip: "Start with the long top horizontal, drop the vertical through its centre, and place the final dot below and to the right so the form feels suspended from the top line.",
    examples: [{ hanzi: "下面", pinyin: "xiàmiàn", meaning: "below; underneath" }, { hanzi: "下课", pinyin: "xiàkè", meaning: "finish class" }, { hanzi: "下来", pinyin: "xiàlái", meaning: "come down" }, { hanzi: "下午", pinyin: "xiàwǔ", meaning: "afternoon" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "猫在桌子下面。", pinyin: "Māo zài zhuōzi xiàmiàn.", meaning: "The cat is under the table." }, { learningLabel: "Developing", hanzi: "下课以后我们去吃饭。", pinyin: "Xiàkè yǐhòu wǒmen qù chīfàn.", meaning: "After class we are going to eat." }, { learningLabel: "Stretch", hanzi: "你下车以后往前走，我在路口等你。", pinyin: "Nǐ xià chē yǐhòu wǎng qián zǒu, wǒ zài lùkǒu děng nǐ.", meaning: "After you get off, walk ahead and I will wait at the intersection." }],
    commonMistake: "Do not raise the final dot above the top line or turn it into a second horizontal; all additional strokes belong below the main reference line.",
    confusableCharacter: { character: "上", guidance: "下 hangs its extra strokes beneath the main horizontal, whereas 上 builds its short mark and vertical relationship above a long baseline." },
    relatedCharacters: ["上", "去", "来"],
    seoDescription: "Learn 下 (xià) stroke order plus below, downward, class-ending, and next-time uses, with 上 vs 下 guidance, graded examples, and worksheets.",
  }),
  guide({
    character: "大", pinyin: "dà", meaning: "big; large; major", strokes: 3, radical: "大", traditional: "大", structure: "Single-component", learningTier: "Beginner",
    hsk: [hsk("2.0", "1", "大"), hsk("3.0", "1", "大")],
    importance: "大 is a basic size adjective that also marks age, importance, institutions, and degree across many beginner word families.",
    components: [{ character: "大", explanation: "A central horizontal crosses the long left fall and right-falling finishing stroke, suggesting an open human figure." }],
    readingNotes: "大 is dà with a falling tone. In 大夫 meaning doctor, the common northern reading is dàifu, a special lexical pattern worth learning as a whole.",
    useNotes: "Place 大 before a noun in compounds such as 大学, or after 很 for description. Asking 多大 usually concerns age or size, depending on the noun and situation.",
    usageTitle: "Size, scale, and importance",
    usage: "大 describes physical size but also expands to major institutions, older age, strong degree, and social importance. It is most useful when contrasted with 小 and learned inside complete noun phrases rather than treated as a universal translation for every kind of ‘big’.",
    writingTip: "Keep the horizontal near the upper middle, draw the left-falling stroke through it, and open the final right-falling stroke broadly enough to balance the character's two sides.",
    examples: [{ hanzi: "大学", pinyin: "dàxué", meaning: "university" }, { hanzi: "大家", pinyin: "dàjiā", meaning: "everyone" }, { hanzi: "多大", pinyin: "duō dà", meaning: "how old; how large" }, { hanzi: "大人", pinyin: "dàrén", meaning: "adult" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "这个苹果很大。", pinyin: "Zhège píngguǒ hěn dà.", meaning: "This apple is big." }, { learningLabel: "Developing", hanzi: "我姐姐在大学学习。", pinyin: "Wǒ jiějie zài dàxué xuéxí.", meaning: "My older sister studies at university." }, { learningLabel: "Stretch", hanzi: "城市很大，但是公共交通很方便。", pinyin: "Chéngshì hěn dà, dànshì gōnggòng jiāotōng hěn fāngbiàn.", meaning: "The city is large, but public transport is convenient." }],
    commonMistake: "Do not write the two falling strokes as a closed 人 below a separate horizontal; all three strokes must cross and open from one balanced centre.",
    confusableCharacter: { character: "太", guidance: "大 has three strokes, while 太 adds a dot below the central crossing; that small final mark changes both shape and meaning." },
    relatedCharacters: ["小", "人", "家"],
    seoDescription: "Learn 大 (dà) with its open three-stroke form, size and degree meanings, contrast with 小 and 太, high-frequency words, and printable practice.",
  }),
  guide({
    character: "小", pinyin: "xiǎo", meaning: "small; little; young", strokes: 3, radical: "小", traditional: "小", structure: "Single-component", learningTier: "Beginner",
    hsk: [hsk("2.0", "1", "小"), hsk("3.0", "1", "小")],
    importance: "小 describes size, youth, limited quantity, and familiar places such as 小学 and 小时 in foundational vocabulary.",
    components: [{ character: "小", explanation: "A central hook anchors two separating side dots, creating a compact three-part form." }],
    readingNotes: "小 is xiǎo with a third tone. It can be descriptive, part of a fixed compound, or an affectionate prefix before a name.",
    useNotes: "Use 小 before a noun for size or category, as in 小猫 and 小学. 小时 means an hour and should be learned as one time word, not translated character by character.",
    usageTitle: "Small size, youth, and familiar categories",
    usage: "小 contrasts physical scale with 大, but it also helps classify early schooling, short amounts of time, younger people, and affectionate names. The surrounding noun tells whether the idea is literal size, age, or a conventional label.",
    writingTip: "Write the central vertical hook first and keep it upright; place the two side dots at similar heights with enough air between them to avoid a cramped 水-like form.",
    examples: [{ hanzi: "小时", pinyin: "xiǎoshí", meaning: "hour" }, { hanzi: "小学", pinyin: "xiǎoxué", meaning: "primary school" }, { hanzi: "小孩", pinyin: "xiǎohái", meaning: "child" }, { hanzi: "大小", pinyin: "dàxiǎo", meaning: "size" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "这只猫很小。", pinyin: "Zhè zhī māo hěn xiǎo.", meaning: "This cat is small." }, { learningLabel: "Developing", hanzi: "我家离小学很近。", pinyin: "Wǒ jiā lí xiǎoxué hěn jìn.", meaning: "My home is close to the primary school." }, { learningLabel: "Stretch", hanzi: "这个箱子太小，放不下所有的书。", pinyin: "Zhège xiāngzi tài xiǎo, fàng bu xià suǒyǒu de shū.", meaning: "This box is too small to hold all the books." }],
    commonMistake: "Do not cross the side dots through the central stroke or add a fourth dot; 小 keeps one hooked centre and two clearly separate outer marks.",
    confusableCharacter: { character: "少", guidance: "少 starts from the 小-like shape but adds a longer lower left-falling stroke; count the strokes and check the extended bottom." },
    relatedCharacters: ["大", "学", "家"],
    seoDescription: "Write 小 (xiǎo) correctly and distinguish small size, youth, 小时, and 小学 through three-stroke guidance, 大 vs 小 examples, and practice sheets.",
  }),
  guide({
    character: "家", pinyin: "jiā", meaning: "home; family; specialist", strokes: 10, radical: "宀", traditional: "家", structure: "Top-bottom", learningTier: "Beginner",
    hsk: [hsk("2.0", "1", "家"), hsk("3.0", "1", "家")],
    importance: "家 ties together home, family members, households, and professions, making it a central character in personal introductions.",
    components: [{ character: "宀", explanation: "The roof component spans the top and establishes the character's width." }, { character: "豕", explanation: "The lower component fills the house with curved and sweeping strokes that need vertical space." }],
    readingNotes: "家 is jiā with a high level first tone. As a suffix, it names a specialist or school of thought, as in 作家 and 科学家.",
    useNotes: "Use 家 for home or household, 家人 for family members, and a number plus 家 to count businesses. Its specialist suffix is productive but attaches to established profession words.",
    usageTitle: "Home, household, and professional identity",
    usage: "家 can be the physical home, the family connected to it, a classifier for shops and companies, or a suffix for experts. Those senses share one character but belong to different sentence frames, so examples should cover people, places, and roles.",
    writingTip: "Set a broad but shallow 宀 roof, centre 豕 below it, and allow the lower curved sweep to extend without touching the roof or leaning the whole character rightward.",
    examples: [{ hanzi: "家人", pinyin: "jiārén", meaning: "family members" }, { hanzi: "大家", pinyin: "dàjiā", meaning: "everyone" }, { hanzi: "回家", pinyin: "huíjiā", meaning: "go home" }, { hanzi: "作家", pinyin: "zuòjiā", meaning: "writer" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我爱我的家。", pinyin: "Wǒ ài wǒ de jiā.", meaning: "I love my home." }, { learningLabel: "Developing", hanzi: "周末我们全家一起吃饭。", pinyin: "Zhōumò wǒmen quánjiā yìqǐ chīfàn.", meaning: "Our whole family eats together at the weekend." }, { learningLabel: "Stretch", hanzi: "她想成为一名写儿童故事的作家。", pinyin: "Tā xiǎng chéngwéi yì míng xiě értóng gùshi de zuòjiā.", meaning: "She wants to become a writer of children's stories." }],
    commonMistake: "Do not make 宀 so narrow that the lower strokes escape on both sides; the roof should cover 豕 while leaving a clean vertical gap.",
    confusableCharacter: { character: "嫁", guidance: "家 begins directly with the roof 宀, while 嫁 adds the woman radical 女 on the left and places 家 as its right component." },
    relatedCharacters: ["人", "大", "小"],
    seoDescription: "Explore 家 (jiā): ten-stroke balance under 宀, home and family meanings, the specialist suffix, common compounds, sentences, and worksheet practice.",
  }),
  guide({
    character: "水", pinyin: "shuǐ", meaning: "water", strokes: 4, radical: "水", traditional: "水", structure: "Single-component", learningTier: "Beginner",
    hsk: [hsk("2.0", "1", "水"), hsk("3.0", "1", "水")],
    importance: "水 is a concrete survival noun, a component behind the 氵 radical, and the base of many drink, weather, and geography words.",
    components: [{ character: "水", explanation: "A central vertical hook is crossed by flowing left and right strokes; in compounds it often changes to 氵." }],
    readingNotes: "水 is shuǐ with a third tone. In compounds such as 水果 and 水平, it keeps the same syllable while the combined meaning changes.",
    useNotes: "Use 水 for water as a substance or drink, and learn its 氵 side form in characters connected with liquids, washing, rivers, or flow, such as 没 and 海.",
    usageTitle: "Water, liquids, and a radical family",
    usage: "水 works as an independent noun and as the conceptual source of the three-dot water radical. Everyday phrases cover drinking, fruit, rivers, and temperature, while character study reveals how the same idea compresses into 氵 on the left of larger forms.",
    writingTip: "Keep the vertical hook centred, make the left stroke compact, and let the right-side movement open in two stages so the character flows without becoming the three-dot radical 氵.",
    examples: [{ hanzi: "喝水", pinyin: "hē shuǐ", meaning: "drink water" }, { hanzi: "水果", pinyin: "shuǐguǒ", meaning: "fruit" }, { hanzi: "开水", pinyin: "kāishuǐ", meaning: "boiled water" }, { hanzi: "水平", pinyin: "shuǐpíng", meaning: "level; standard" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我想喝水。", pinyin: "Wǒ xiǎng hē shuǐ.", meaning: "I want to drink water." }, { learningLabel: "Developing", hanzi: "桌上的水有一点儿热。", pinyin: "Zhuō shàng de shuǐ yǒu yìdiǎnr rè.", meaning: "The water on the table is a little hot." }, { learningLabel: "Stretch", hanzi: "运动以后要慢慢喝水，不要一次喝太多。", pinyin: "Yùndòng yǐhòu yào mànmàn hē shuǐ, bú yào yí cì hē tài duō.", meaning: "After exercising, drink water slowly rather than too much at once." }],
    commonMistake: "Do not write 水 as three left-side dots; the standalone character has a central hook and balanced spreading strokes on both sides.",
    confusableCharacter: { character: "永", guidance: "水 and 永 share flowing stroke shapes, but 永 begins with a top dot and a different central turning sequence; do not copy one order onto the other." },
    relatedCharacters: ["喝", "没", "吃"],
    seoDescription: "Learn 水 (shuǐ) as a four-stroke character and the source of 氵, with drink and fruit vocabulary, confusable forms, graded sentences, and grids.",
  }),
  guide({
    character: "书", pinyin: "shū", meaning: "book; document; to write", strokes: 4, radical: "乛", traditional: "書", structure: "Single-component", learningTier: "Beginner",
    hsk: [hsk("2.0", "1", "书"), hsk("3.0", "1", "书")],
    importance: "书 is the core book character for reading, libraries, school materials, and the written-language word family.",
    components: [{ character: "书", explanation: "The simplified form uses compact turns around a long central vertical and ends with a right-side dot." }],
    readingNotes: "书 is shū with a high level first tone. The syllable remains stable in 看书, 书店, 图书馆, and 书法.",
    useNotes: "Use 书 as a countable noun with the classifier 本, 看书 for reading, and 书法 for calligraphy. 写书 means authoring a book, not simply writing in one.",
    usageTitle: "Books, reading, and written culture",
    usage: "书 names a book and extends into places, activities, and art forms connected with written texts. Its classifier 本 is especially important, while the traditional form 書 is visually different enough to learn as a separate recognition target.",
    writingTip: "Keep the upper turns compact, run the central vertical cleanly through the form, and place the final dot distinctly to the right rather than attaching it to the main line.",
    examples: [{ hanzi: "看书", pinyin: "kàn shū", meaning: "read a book" }, { hanzi: "书店", pinyin: "shūdiàn", meaning: "bookshop" }, { hanzi: "书法", pinyin: "shūfǎ", meaning: "calligraphy" }, { hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "library" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "这是我的书。", pinyin: "Zhè shì wǒ de shū.", meaning: "This is my book." }, { learningLabel: "Developing", hanzi: "她常常在图书馆看书。", pinyin: "Tā chángcháng zài túshūguǎn kàn shū.", meaning: "She often reads in the library." }, { learningLabel: "Stretch", hanzi: "这本书的故事不长，但是很有意思。", pinyin: "Zhè běn shū de gùshi bù cháng, dànshì hěn yǒuyìsi.", meaning: "The story in this book is not long, but it is interesting." }],
    commonMistake: "Do not add extra horizontal lines from the traditional form 書 or merge the final dot into the central stroke; simplified 书 has only four strokes.",
    confusableCharacter: { character: "事", guidance: "书 is a compact four-stroke form with a final dot, while 事 has a longer stacked centre and several additional horizontals and turns." },
    relatedCharacters: ["学", "一", "家"],
    seoDescription: "Master 书 (shū) in four strokes, recognize 書, use 本 as its classifier, study reading and library words, and make a printable book-word worksheet.",
  }),
  guide({
    character: "吃", pinyin: "chī", meaning: "to eat", strokes: 6, radical: "口", traditional: "吃", structure: "Left-right", learningTier: "Beginner",
    hsk: [hsk("2.0", "1", "吃"), hsk("3.0", "1", "吃")],
    importance: "吃 drives food, meal, invitation, and preference sentences, making it one of the most productive beginner action characters.",
    components: [{ character: "口", explanation: "The mouth radical is small and square on the left." }, { character: "乞", explanation: "The right component is taller, beginning with a short left fall and ending in a curved hook." }],
    readingNotes: "吃 is chī with a high, level first tone. Keep the retroflex ch sound distinct from q in words such as 七 qī.",
    useNotes: "Use 吃 before food or a meal word, and 吃饭 as the broad everyday expression for eating a meal. 好吃 describes food as tasty; it does not mean ‘eat well’.",
    usageTitle: "Eating, meals, and taste",
    usage: "吃 takes foods and meals as objects, appears in invitations, and builds result or taste expressions with other characters. A useful beginner contrast is 吃 for solids or meals and 喝 for liquids, while 好吃 evaluates the food itself.",
    writingTip: "Keep 口 narrow and slightly raised, give 乞 more height on the right, and finish its curved hook with open space below instead of crowding it against the mouth radical.",
    examples: [{ hanzi: "吃饭", pinyin: "chīfàn", meaning: "eat a meal" }, { hanzi: "好吃", pinyin: "hǎochī", meaning: "tasty" }, { hanzi: "吃完", pinyin: "chīwán", meaning: "finish eating" }, { hanzi: "小吃", pinyin: "xiǎochī", meaning: "snack; street food" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "我吃米饭。", pinyin: "Wǒ chī mǐfàn.", meaning: "I eat rice." }, { learningLabel: "Developing", hanzi: "你想吃中国菜吗？", pinyin: "Nǐ xiǎng chī Zhōngguó cài ma?", meaning: "Would you like to eat Chinese food?" }, { learningLabel: "Stretch", hanzi: "这家小店的面很好吃，我们下次再来。", pinyin: "Zhè jiā xiǎodiàn de miàn hěn hǎochī, wǒmen xià cì zài lái.", meaning: "The noodles at this small shop are delicious; we will come again." }],
    commonMistake: "Do not enlarge 口 until both sides are equal or write the final hook of 乞 as a closed box; the right side must remain taller and open.",
    confusableCharacter: { character: "喝", guidance: "Both start with 口, but 吃 has the simpler 乞 on the right and means eat, while 喝 has the denser 曷 component and means drink." },
    relatedCharacters: ["喝", "好", "水"],
    seoDescription: "Learn 吃 (chī) stroke order, retroflex pronunciation, meal patterns, 好吃, and the 吃 vs 喝 distinction with food vocabulary and worksheets.",
  }),
  guide({
    character: "喝", pinyin: "hē", meaning: "to drink", strokes: 12, radical: "口", traditional: "喝", structure: "Left-right", learningTier: "Beginner",
    hsk: [hsk("2.0", "1", "喝"), hsk("3.0", "1", "喝")],
    importance: "喝 is the everyday action for water, tea, coffee, and other drinks, and pairs naturally with food routines.",
    components: [{ character: "口", explanation: "The compact mouth radical sits on the left." }, { character: "曷", explanation: "The taller right component stacks 日 above a hooked, enclosed lower movement." }],
    readingNotes: "喝 is normally hē with a first tone for drinking. The fourth-tone hè occurs in words about shouting or cheering, such as 喝彩.",
    useNotes: "Use 喝 with beverages, soups in some contexts, and medicine when the medicine is liquid. Contrast 吃 for food and for taking pills in ordinary speech.",
    usageTitle: "Drinks, thirst, and liquid routines",
    usage: "喝 selects liquids as its typical object and supports invitations, habits, and health instructions. The alternate hè reading belongs to a separate shouting word family, so pronunciation must follow the whole word rather than the character alone.",
    writingTip: "Write a small 口 first, stack the upper 日 of 曷 neatly, and preserve the open curve and interior 人-like strokes at the lower right without flattening them.",
    examples: [{ hanzi: "喝水", pinyin: "hē shuǐ", meaning: "drink water" }, { hanzi: "喝茶", pinyin: "hē chá", meaning: "drink tea" }, { hanzi: "好喝", pinyin: "hǎohē", meaning: "tastes good to drink" }, { hanzi: "喝完", pinyin: "hēwán", meaning: "finish drinking" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "请喝水。", pinyin: "Qǐng hē shuǐ.", meaning: "Please drink some water." }, { learningLabel: "Developing", hanzi: "爸爸早上喜欢喝咖啡。", pinyin: "Bàba zǎoshang xǐhuan hē kāfēi.", meaning: "Dad likes drinking coffee in the morning." }, { learningLabel: "Stretch", hanzi: "天气很热，你运动以后要多喝一点儿水。", pinyin: "Tiānqì hěn rè, nǐ yùndòng yǐhòu yào duō hē yìdiǎnr shuǐ.", meaning: "It is hot, so drink more water after exercising." }],
    commonMistake: "Do not simplify the right side into 乞 as in 吃; 喝 requires the full stacked 曷 component with a visible upper 日.",
    confusableCharacter: { character: "吃", guidance: "喝 and 吃 share the mouth radical, but the right components, stroke counts, and object types differ: liquids versus foods or meals." },
    relatedCharacters: ["吃", "水", "好"],
    seoDescription: "Study 喝 (hē/hè) with twelve-stroke structure, drinks vocabulary, alternate pronunciation, 吃 vs 喝 guidance, graded sentences, and practice grids.",
  }),
  guide({
    character: "二", pinyin: "èr", meaning: "two", strokes: 2, radical: "二", traditional: "二", structure: "Single-component", learningTier: "High-frequency",
    hsk: [hsk("2.0", "1", "二"), hsk("3.0", "1", "二")],
    importance: "二 is the formal numeral used in counting sequences, dates, mathematics, ordinals, and many fixed number expressions.",
    components: [{ character: "二", explanation: "A short upper horizontal and longer lower horizontal create a simple two-line numeral." }],
    readingNotes: "二 is èr with a falling tone. Tone and word choice both matter: 两 liǎng often replaces 二 before a classifier, while 二 stays in counting and ordinals.",
    useNotes: "Use 二 in phone numbers, dates, arithmetic, 第二, and fixed forms. Use 两 before most classifiers: 两个人, not usually 二个人.",
    usageTitle: "Counting sequences versus classifier phrases",
    usage: "二 names the number two in sequences, labels, dates, mathematics, and ordinal numbers. Mandarin often switches to 两 when counting nouns with a classifier, so learning the distribution between 二 and 两 prevents a very common beginner error.",
    writingTip: "Write the upper horizontal shorter and slightly higher, then place the longer lower horizontal parallel beneath it; avoid equal lengths or a slanted equals-sign shape.",
    examples: [{ hanzi: "二月", pinyin: "èryuè", meaning: "February" }, { hanzi: "第二", pinyin: "dì'èr", meaning: "second" }, { hanzi: "二十", pinyin: "èrshí", meaning: "twenty" }, { hanzi: "一二", pinyin: "yī èr", meaning: "one, two" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "今天是二月二日。", pinyin: "Jīntiān shì èryuè èr rì.", meaning: "Today is February second." }, { learningLabel: "Developing", hanzi: "他在比赛中得了第二名。", pinyin: "Tā zài bǐsài zhōng dé le dì'èr míng.", meaning: "He came second in the competition." }, { learningLabel: "Stretch", hanzi: "这个号码的最后两位是二和六。", pinyin: "Zhège hàomǎ de zuìhòu liǎng wèi shì èr hé liù.", meaning: "The last two digits of this number are two and six." }],
    commonMistake: "Do not make both horizontal strokes identical; the upper one is shorter, and the longer lower line visually supports the numeral.",
    confusableCharacter: { character: "两", guidance: "二 is used in sequences, ordinals, and mathematics; 两 normally precedes a classifier or measure, as in 两个人 and 两本书." },
    relatedCharacters: ["一", "大", "小"],
    seoDescription: "Learn 二 (èr) in two strokes and decide between 二 and 两 for sequences, ordinals, dates, and classifier phrases, with examples and writing practice.",
  }),
  guide({
    character: "再", pinyin: "zài", meaning: "again; then; another", strokes: 6, radical: "冂", traditional: "再", structure: "Single-component", learningTier: "High-frequency",
    hsk: [hsk("2.0", "2", "再"), hsk("3.0", "1", "再")],
    importance: "再 sequences future or repeated actions and appears in farewells, instructions, and plans from early conversation onward.",
    components: [{ character: "再", explanation: "An outer 冂-like frame crosses a centred vertical and stacked inner horizontals before the base closes the form." }],
    readingNotes: "再 is zài with a falling tone, exactly like 在. Meaning and character choice must come from grammar, not sound alone.",
    useNotes: "Use 再 before an action that will happen again or later: 明天再来. Use 在 for location or a progressive action: 在家 or 在学习.",
    usageTitle: "A repeated or later action",
    usage: "再 looks forward to another occurrence or orders one action after another. It commonly appears before the repeated verb, while 又 often reports repetition that has already happened. The homophone 在 belongs to location and ongoing-action grammar.",
    writingTip: "Keep the outer frame upright, centre the vertical through the internal lines, and maintain visible spacing among the three horizontal levels instead of filling the middle.",
    examples: [{ hanzi: "再见", pinyin: "zàijiàn", meaning: "goodbye" }, { hanzi: "再来", pinyin: "zài lái", meaning: "come again" }, { hanzi: "再说", pinyin: "zài shuō", meaning: "discuss later; moreover" }, { hanzi: "一再", pinyin: "yízài", meaning: "repeatedly" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "明天再见。", pinyin: "Míngtiān zàijiàn.", meaning: "See you tomorrow." }, { learningLabel: "Developing", hanzi: "这个字写错了，请再写一次。", pinyin: "Zhège zì xiě cuò le, qǐng zài xiě yí cì.", meaning: "This character is wrong; please write it again." }, { learningLabel: "Stretch", hanzi: "我们先看例句，再自己做练习。", pinyin: "Wǒmen xiān kàn lìjù, zài zìjǐ zuò liànxí.", meaning: "We will read the examples first and then do the exercise ourselves." }],
    commonMistake: "Do not replace the centred internal structure with 土 or omit the middle horizontal; 再 has a framed, layered interior rather than 在's left-side 土.",
    confusableCharacter: { character: "在", guidance: "再 means again or then and usually precedes a future repeated action; 在 marks location or an action currently in progress." },
    relatedCharacters: ["在", "来", "二"],
    seoDescription: "Learn 再 (zài) stroke order and its again/then grammar, compare 再 with 在 and 又, practise sequencing examples, and print a custom worksheet.",
  }),
  guide({
    character: "得", pinyin: "dé / de / děi", meaning: "obtain; complement marker; must", strokes: 11, radical: "彳", traditional: "得", structure: "Left-right", learningTier: "High-frequency",
    hsk: [hsk("2.0", "2", "得"), hsk("3.0", "2", "得")],
    importance: "得 connects verbs to degree complements, expresses obtaining, and carries the common spoken necessity reading děi.",
    components: [{ character: "彳", explanation: "The step radical stays narrow on the left with two descending strokes." }, { character: "㝵", explanation: "The right side stacks 日 above a measured lower horizontal and 寸-like finish." }],
    readingNotes: "得 is dé when it means obtain, neutral-tone de as a complement marker, and děi when it means must. The sentence structure chooses the reading.",
    useNotes: "Place neutral 得 after a verb and before a degree or result phrase: 写得好. Use 得到 for obtain and spoken 得 děi before a verb for necessity.",
    usageTitle: "Three readings, three grammatical jobs",
    usage: "得 cannot be learned from one translation. As dé it belongs to words about gaining; as neutral de it links an action to how well or to what degree it happens; as děi it functions like ‘must’. Position and following words identify the intended reading.",
    writingTip: "Keep 彳 slim, align the stacked right side vertically, and leave a clean separation between 日 and the lower 寸-like strokes so eleven strokes remain readable.",
    examples: [{ hanzi: "得到", pinyin: "dédào", meaning: "obtain; receive" }, { hanzi: "写得好", pinyin: "xiě de hǎo", meaning: "write well" }, { hanzi: "跑得快", pinyin: "pǎo de kuài", meaning: "run fast" }, { hanzi: "我得去", pinyin: "wǒ děi qù", meaning: "I must go" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "你写得很好。", pinyin: "Nǐ xiě de hěn hǎo.", meaning: "You write very well." }, { learningLabel: "Developing", hanzi: "她得到了老师的帮助。", pinyin: "Tā dédào le lǎoshī de bāngzhù.", meaning: "She received the teacher's help." }, { learningLabel: "Stretch", hanzi: "明天要考试，我今晚得早点儿睡。", pinyin: "Míngtiān yào kǎoshì, wǒ jīnwǎn děi zǎodiǎnr shuì.", meaning: "There is an exam tomorrow, so I must sleep earlier tonight." }],
    commonMistake: "Do not choose 得 only because it sounds de; after a noun use 的 for modification, and before an adverbial verb phrase use 地 instead.",
    confusableCharacter: { character: "的/地", guidance: "的 links a modifier to a noun, 地 links an adverbial description to a verb, and 得 follows a verb before a degree or result complement." },
    relatedCharacters: ["的", "地", "好"],
    seoDescription: "Master 得 (dé/de/děi): eleven-stroke form, three readings, verb complements, obtaining and necessity, plus 的得地 comparison and practice.",
  }),
  guide({
    character: "地", pinyin: "de / dì", meaning: "adverb marker; ground; place", strokes: 6, radical: "土", traditional: "地", structure: "Left-right", learningTier: "High-frequency",
    hsk: [hsk("2.0", "3", "地"), hsk("3.0", "1", "地")],
    importance: "地 is both a high-frequency neutral grammar marker before verbs and a content character for ground, land, and place.",
    components: [{ character: "土", explanation: "The earth radical narrows on the left and raises its final horizontal." }, { character: "也", explanation: "The right component uses a broad turning stroke with a final rising hook." }],
    readingNotes: "Read 地 as neutral de when it marks an adverb before a verb, and dì in nouns such as 地方, 地图, and 地面.",
    useNotes: "Use description + 地 + verb for manner, as in 慢慢地说. Use the dì reading in place and ground words. Not every adverb requires a written 地 in natural usage.",
    usageTitle: "Manner marker versus ground and place",
    usage: "地 switches between a grammatical connector and a lexical noun component. Neutral de turns a descriptive phrase into the manner of an action, while dì carries concrete senses of land, surface, or location. Reading the neighboring verb or noun resolves the ambiguity.",
    writingTip: "Compress 土 on the left, give 也 enough width for its long turn, and keep the right hook open; do not let both sides collapse into one square block.",
    examples: [{ hanzi: "慢慢地", pinyin: "mànmàn de", meaning: "slowly" }, { hanzi: "地方", pinyin: "dìfang", meaning: "place" }, { hanzi: "地图", pinyin: "dìtú", meaning: "map" }, { hanzi: "地上", pinyin: "dìshang", meaning: "on the ground" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "请慢慢地说。", pinyin: "Qǐng mànmàn de shuō.", meaning: "Please speak slowly." }, { learningLabel: "Developing", hanzi: "书掉在地上了。", pinyin: "Shū diào zài dìshang le.", meaning: "The book fell onto the ground." }, { learningLabel: "Stretch", hanzi: "她高兴地打开地图，开始介绍这个地方。", pinyin: "Tā gāoxìng de dǎkāi dìtú, kāishǐ jièshào zhège dìfang.", meaning: "She happily opened the map and began introducing the place." }],
    commonMistake: "Do not use 地 after a verb to introduce degree; that position requires 得, while noun modification before a noun generally requires 的.",
    confusableCharacter: { character: "的/得", guidance: "地 normally stands before a verb to mark manner; 的 stands before a noun, and 得 comes after a verb before a complement." },
    relatedCharacters: ["的", "得", "上"],
    seoDescription: "Learn 地 (de/dì) with six-stroke 土+也 structure, adverb-marker and place meanings, 的得地 rules, graded sentences, and handwriting practice.",
  }),
  guide({
    character: "坏", pinyin: "huài", meaning: "bad; broken; to spoil", strokes: 7, radical: "土", traditional: "壞", structure: "Left-right", learningTier: "Beginner",
    hsk: [hsk("2.0", "3", "坏"), hsk("3.0", "1", "坏")],
    importance: "坏 provides the everyday opposite of 好 for quality, behavior, damage, spoiled food, weather, and failed equipment.",
    components: [{ character: "土", explanation: "The narrow earth radical uses a rising final stroke on the left." }, { character: "不", explanation: "The right side keeps 不 compact with a clear central vertical and final dot." }],
    readingNotes: "坏 is huài with a falling tone. It can describe a negative quality or indicate that an object has become broken or spoiled.",
    useNotes: "Use 很坏 for bad quality or behavior, 坏了 for a changed broken state, and 坏人 for a bad person. Context separates moral judgment from physical failure.",
    usageTitle: "Bad quality, damage, and spoiled states",
    usage: "坏 evaluates something negatively and also reports malfunction, breakage, or spoilage. The sentence-final 了 often signals a new damaged state, while a noun after 坏 can create a category such as 坏人. Pair it with 好 to practise a clear evaluation contrast.",
    writingTip: "Keep 土 narrow and slightly higher, write 不 fully on the right, and leave a slim gap so the final dot remains visible instead of merging into the radical.",
    examples: [{ hanzi: "坏人", pinyin: "huàirén", meaning: "bad person" }, { hanzi: "坏了", pinyin: "huài le", meaning: "is broken; went bad" }, { hanzi: "坏事", pinyin: "huàishì", meaning: "bad thing" }, { hanzi: "好坏", pinyin: "hǎohuài", meaning: "quality; good or bad" }],
    exampleSentences: [{ learningLabel: "Starter", hanzi: "这个苹果坏了。", pinyin: "Zhège píngguǒ huài le.", meaning: "This apple has gone bad." }, { learningLabel: "Developing", hanzi: "电脑坏了，我今天不能工作。", pinyin: "Diànnǎo huài le, wǒ jīntiān bù néng gōngzuò.", meaning: "The computer is broken, so I cannot work today." }, { learningLabel: "Stretch", hanzi: "天气虽然很坏，但是比赛没有取消。", pinyin: "Tiānqì suīrán hěn huài, dànshì bǐsài méiyǒu qǔxiāo.", meaning: "Although the weather is bad, the match was not cancelled." }],
    commonMistake: "Do not expand 土 to half the character's full width or omit the right-side dot in 不; the contrast between narrow and broad sides keeps 坏 legible.",
    confusableCharacter: { character: "好", guidance: "坏 evaluates something negatively or broken, while 好 evaluates it positively or ready; their structures and components are completely different." },
    relatedCharacters: ["好", "不", "没"],
    seoDescription: "Learn 坏 (huài) in seven strokes, distinguish bad quality from a broken-state 坏了, compare 好 vs 坏, and practise useful sentences on grids.",
  }),
];
