import { isChineseLocale } from "./i18n";

const chinese: Readonly<Record<string, string>> = {
  "Worksheet Maker": "字帖生成器", "HSK Lists": "HSK 词表", "Compare": "易混字对比",
  "Templates": "字帖模板", "Stroke Order": "笔顺", "Printable Grids": "空白格纸",
  "Create Worksheet": "制作字帖", "Create": "制作", "Open navigation": "打开导航",
  "All Templates": "全部模板", "All templates": "全部模板", "Quick Start": "快速入门",
  "HSK Worksheets": "HSK 字帖", "Writing Basics": "书写基础", "Everyday Words": "日常词汇",
  "Stroke Order Tool": "笔顺查询", "Stroke Order Rules": "笔顺规则", "Character Components": "汉字部件",
  "Continuous Practice": "连续练习", "Practice Sheets": "练习字帖", "Basic Strokes": "基本笔画",
  "Radicals": "偏旁部首", "All Printable Grids": "全部格纸", "Tian Zi Ge PDF": "田字格 PDF",
  "Mi Zi Ge PDF": "米字格 PDF", "Blank Writing Paper": "空白练字纸", "Family": "家庭",
  "Numbers": "数字", "Colors": "颜色", "Teaching tools": "教学工具", "Worksheet Generator": "字帖生成器",
  "Practice Types": "练习方式", "Resources": "学习资源", "For Teachers": "教师备课",
  "HSK Vocabulary": "HSK 词汇", "HSK Level Checker": "HSK 等级检测", "Character Comparisons": "易混字对比",
  "Make a Chinese worksheet from your own word list. Edit it, print it, and use it again when the class is ready to review.": "用自己的词表制作汉字字帖。编辑、打印，也可以在复习时再次使用。",
  "Questions or feedback? Contact us:": "遇到问题或有建议？联系我们：",
  "Free Chinese Character Worksheet Generator": "免费汉字字帖生成器",
  "Use this free Chinese character worksheet generator to turn your own English or Chinese word list into printable practice sheets. Edit the Hanzi and Pinyin, choose tracing, Tian Zi Ge, Mi Zi Ge, or blank writing grids, then download an A4 or US Letter PDF—no sign-up required.": "粘贴中文或英文词表，核对汉字和拼音，选择练习方式，即可下载 A4 或美式信纸 PDF。免费使用，无需注册。",
  "Free to use": "免费使用", "No sign-up": "无需注册", "A4 & US Letter": "A4 / 美式信纸",
  "Build from my word list": "用自己的词表制作", "Start with a worksheet": "从模板开始",
  "Check one character’s stroke order": "查询单字笔顺",
  "Paste English or Chinese words and make a custom worksheet.": "粘贴中文或英文，制作自己的字帖。",
  "Pick an editable topic or HSK word list to get started faster.": "选择主题或 HSK 词表，快速开始。",
  "Look up the strokes before adding a character to your worksheet.": "先查看笔顺，再把汉字加入字帖。",
  "One site, clear starting points": "按需要选择入口", "Choose the Right Chinese Writing Tool": "找到适合你的汉字练习工具",
  "Start with the page that matches the job: build from your own words, open a ready-made list, print empty grids, or focus on vocabulary and stroke order.": "用自己的词汇制作字帖、选择现成模板、打印空白格纸，或练习词汇与笔顺。",
  "Chinese worksheet generator from your word list": "用自己的词表生成字帖",
  "Printable Chinese writing worksheets": "可打印汉字字帖",
  "Tian Zi Ge and Mi Zi Ge PDFs": "田字格与米字格 PDF", "HSK vocabulary lists": "HSK 词表",
  "Chinese stroke order guides": "汉字笔顺指南", "English to Chinese writing practice": "英文转中文书写练习",
  "Edit Hanzi and Pinyin before printing a custom practice sheet.": "打印前可以逐项修改汉字和拼音。",
  "Choose an editable topic, classroom, or HSK word list.": "选择可编辑的主题、课堂或 HSK 词表。",
  "Download blank Hanzi grid paper for immediate handwriting practice.": "下载空白汉字格纸，开始书写练习。",
  "Compare HSK 2.0 and 3.0 levels, then send selected words to a worksheet.": "比较 HSK 2.0 和 3.0，选择词条加入字帖。",
  "Check one character’s strokes, meaning, and practice options.": "查看单字的笔顺、含义和练习方式。",
  "Begin with English vocabulary, then review the matched Hanzi and Pinyin.": "从英文词汇开始，核对匹配的汉字与拼音。",
  "Practice sheet workflow": "制作步骤", "How to Use the Chinese Character Worksheet Generator": "怎样制作一张字帖",
  "GridHanzi keeps the worksheet useful first: paste vocabulary, review the Chinese writing fields, then print a practice sheet with grids, Pinyin, and optional stroke-order guidance.": "粘贴词汇、核对内容，再打印带格线、拼音和可选笔顺的字帖。",
  "Create a practice sheet": "制作练习字帖", "Paste words": "粘贴词汇", "Check Hanzi and Pinyin": "核对汉字与拼音", "Print the PDF": "下载或打印 PDF",
  "Start with English, Chinese, or a mixed classroom word list.": "支持中文、英文及混合课堂词表。",
  "Edit every row before it becomes a printable worksheet.": "打印前，每个词条都可以修改。",
  "Choose tracing grids, blank writing cells, paper size, and PDF output.": "选择描红、空白练习格、纸张和 PDF 输出。",
  "Need a faster start? Browse": "想快速开始？浏览", "Chinese character practice sheet templates": "汉字字帖模板",
  "and open any topic in the worksheet generator. Need empty practice cells instead? Download": "，选择主题进入生成器。只需要空白格纸？下载",
  "printable Hanzi grid PDFs": "可打印汉字格纸 PDF", "Editable word lists": "可编辑词表",
  "Start with a Chinese worksheet template": "从字帖模板开始", "View all templates": "查看全部模板",
  "words": "个词", "View": "查看", "worksheet": "字帖", "One list, three uses": "一份词表，三种练习",
  "Choose a Chinese character practice mode": "选择汉字练习方式", "Learn new characters": "学习新字",
  "Practice handwriting": "描红临写", "Test recall": "默写测试", "Try this mode": "使用这种方式",
  "See the strokes in order, trace the character, then copy it.": "先看笔顺，再描红，最后独立书写。",
  "Start with a model and tracing cells, then use the blank grids.": "先看示范字和描红格，再使用空白格练习。",
  "Read the Pinyin or meaning, then write the word without a model.": "根据拼音或词义默写，不显示示范字。",
  "For regular lesson prep": "日常备课", "Create Chinese writing worksheets for class": "为课堂制作汉字字帖",
  "Paste this week’s words": "粘贴本周词汇", "Check bilingual fields": "核对双语内容", "Print practice and quizzes": "打印练习与测验",
  "Copy them from your lesson plan or spreadsheet.": "从教案或表格中直接复制。",
  "Fix the Hanzi, Pinyin, or meaning if needed.": "按需要修改汉字、拼音和词义。",
  "Use the same list for tracing and a later test.": "同一份词表可用于描红和之后的测验。",
  "Use one list for lessons, practice, and review": "一份词表，完成教学、练习与复习",
  "Turn the same checked vocabulary into a guided lesson, a handwriting page, or a short recall test.": "把核对好的词表转换为笔顺教学、书写练习或默写测验。",
  "Learn pages with stroke order": "带笔顺的教学页", "Tracing and blank writing grids": "描红与空白练习格",
  "Tests without a model character": "不显示示范字的测验", "A4, US Letter, and tablet PDFs": "A4、美式信纸和平板 PDF",
  "See the teacher workflow": "查看教师备课流程", "Create a worksheet": "制作字帖",
  "Practice at home": "在家练习", "Print Chinese character practice sheets for home": "打印适合家庭练习的汉字字帖",
  "Print the words from class and let your child trace them before writing them without a model. No extra app or account is needed.": "打印课堂词汇，让孩子先描红，再独立书写。无需额外应用或账号。",
  "Review this week’s words": "复习本周词汇", "Trace before writing independently": "先描红，再独立书写", "Print another copy for later review": "需要复习时再打印一份",
  "Questions before you print": "打印前的常见问题", "Frequently asked questions": "常见问题",
  "Worksheet workflow": "字帖制作流程", "How the Chinese worksheet generator works": "怎样使用字帖生成器",
  "Start with English or Chinese vocabulary, review the generated Hanzi and Pinyin, then print the same list as a lesson page, handwriting practice sheet, or short recall test.": "输入中文或英文，核对生成的汉字与拼音，然后选择教学、书写练习或默写测试。",
  "Starting from translations? Open the dedicated": "从英文开始？打开", "page for an editable starter list.": "页面，使用可编辑的入门词表。",
  "Browse editable templates": "浏览可编辑模板", "Printable grid PDFs": "空白格纸 PDF",
  "Paste a word list": "粘贴词表", "Choose writing settings": "选择练习设置", "Preview and print": "预览并打印",
  "Add English, Chinese, or mixed vocabulary. The editor keeps every row editable before you print.": "添加中文、英文或混合词汇。打印前仍可逐项修改。",
  "Set the grid, cell size, Pinyin, stroke-order guidance, paper size, and practice mode for a Mandarin worksheet or Hanzi grid paper.": "调整格子、尺寸、拼音、笔顺、纸张和练习方式。",
  "Check the live preview, open the full print page, then save a PDF or send the worksheet to a printer.": "检查实时预览，打开完整页面，然后下载 PDF 或打印。",
  "Printable worksheet controls": "字帖设置", "Worksheet settings teachers and parents expect": "适合教师与家长的练习设置",
  "Tian Zi Ge and Mi Zi Ge Hanzi grid paper": "田字格与米字格", "Tracing, handwriting practice, and recall test modes": "新字精学、描红临写和默写测试",
  "Optional Pinyin and stroke-order guidance": "可选拼音与笔顺引导", "A4, US Letter, and tablet PDF formats": "A4、美式信纸和平板 PDF",
  "Example worksheets": "字帖示例", "Examples you can generate and edit": "可以直接编辑的字帖示例",
  "Family practice sheet": "家庭词汇字帖", "Numbers writing worksheet": "数字字帖", "Colors practice sheet": "颜色字帖", "HSK 1 writing practice": "HSK 一级书写练习",
  "Generator FAQ": "生成器常见问题", "Chinese worksheet generator questions": "字帖生成器使用问答",
  "Home": "首页", "Home / Templates": "首页 / 字帖模板", "Printable Chinese Writing Worksheets": "可打印的汉字字帖",
  "Choose a ready-made topic, Pinyin, or HSK worksheet, then edit the Hanzi, grid, and paper size before saving a PDF.": "选择主题、拼音或 HSK 模板，修改汉字、格子和纸张后下载 PDF。",
  "Editable practice sheets": "可编辑练习纸", "Chinese Character Practice Sheet Templates": "汉字练习字帖模板",
  "Start from printable Chinese writing practice sheets for family, numbers, colors, HSK, school, travel, Pinyin, and everyday topics. Each template opens as an editable word list, so you can change the Hanzi, Pinyin, grid, paper size, and PDF layout before printing.": "从家庭、数字、颜色、HSK、校园、旅行等主题开始。每份模板都可修改词汇、拼音、格子和纸张设置。",
  "Make a custom worksheet": "自定义字帖", "Blank grid PDFs": "空白格纸 PDF", "Teacher workflow": "教师备课流程",
  "Choose by HSK version": "按 HSK 版本选词", "Browse HSK vocabulary": "浏览 HSK 词汇",
  "Real worksheet outcomes": "字帖效果", "See what you can print": "看看可以打印什么",
  "Compare the finished page direction first. Every example stays editable before you print or save a PDF.": "先选择适合的练习版式，打印或下载前仍可修改。",
  "Preview → edit → print": "预览 → 编辑 → 打印", "Printable": "可打印", "Use this layout": "使用此版式",
  "Browse by need": "按需要查找", "Find the right worksheet faster": "快速找到合适的字帖", "templates": "份模板",
  "Edit sheet": "编辑字帖", "Details": "详情", "Search templates": "搜索模板", "All worksheet templates": "全部字帖模板",
  "Edit this practice sheet": "编辑这份字帖", "Worksheet details": "字帖详情", "No templates found": "没有找到模板",
  "Try another word or clear the filters.": "试试其他关键词，或清除筛选条件。", "Reset filters": "重置筛选",
  "Choose a worksheet": "选择字帖", "Pick a topic and review the words before students start writing.": "选择主题，在学生开始书写前核对词表。",
  "Trace a model character, then write it again in blank grids.": "先描红示范字，再在空白格中练习。",
  "Filter by HSK level and print the words your learner is studying.": "按 HSK 等级筛选，打印正在学习的词汇。",
  "All": "全部", "Use the filters above": "使用上方筛选", "For first characters": "适合初学汉字", "For HSK review": "适合 HSK 复习", "For everyday vocabulary": "适合日常词汇",
  "Large, calm writing targets for a learner's first printable page.": "大格子，适合初学者的第一张字帖。",
  "Turn a level-based vocabulary set into editable recognition and writing practice.": "把分级词表转换为认读和书写练习。",
  "Start from a useful topic, then tune the guidance and blank writing space.": "从实用主题开始，调整引导强度和空白练习空间。",
  "Kids": "儿童", "Adult": "成人", "Tablet": "平板", "Brush": "毛笔", "HB / 2B pencil": "HB / 2B 铅笔",
  "0.38–0.5 mm pen": "0.38–0.5 mm 签字笔", "Apple Pencil / stylus": "Apple Pencil / 触控笔", "Chinese brush": "毛笔",
  "Large, guided grids for early learners": "大格子与书写引导，适合初学者", "Compact repetition for fluent handwriting": "紧凑的重复练习，适合熟练书写",
  "Flashcards": "闪卡", "Card": "卡片", "Name:": "姓名：", "Date:": "日期：",
  "What can I make with this Chinese character worksheet generator?": "可以用它制作哪些字帖？",
  "This Chinese worksheet generator turns any English or Chinese vocabulary list into editable practice pages with Hanzi, Pinyin, tracing cells, blank writing grids, Hanzi grid paper, and optional stroke-order guidance.": "可以制作带汉字、拼音、描红、空白格和可选笔顺的练习纸。常用词可自动补全，未匹配词需要手动填写。",
  "Is the printable Chinese worksheet generator free?": "生成和打印字帖需要付费吗？",
  "Yes. You can create, edit, preview, download, and print complete worksheets without creating an account.": "免费，无需注册即可制作、编辑、预览、下载和打印。",
  "Does the Hanzi practice sheet generator include Pinyin and stroke order?": "字帖可以显示拼音和笔顺吗？",
  "Yes. Common vocabulary can be filled with Hanzi, Pinyin, and English meanings. You can review every field and choose whether to show Pinyin and stroke-order guidance before downloading.": "可以。常用词会补全汉字、拼音和英文释义，下载前可以修改并选择是否显示拼音和笔顺。",
  "Which paper sizes and writing profiles are supported?": "支持哪些纸张和书写模板？",
  "Choose A4 or US Letter for printing, or a 3:4 digital worksheet for tablet apps. Kids, Adult, Tablet, and Brush profiles adjust the grid size and layout for different writing tools.": "支持 A4、美式信纸和 3:4 平板 PDF；儿童、成人、平板及毛笔模板会调整格子尺寸。",
  "Can I print Hanzi grid paper or Chinese character grids?": "可以打印空白格纸吗？",
  "Yes. Use Tian Zi Ge or Mi Zi Ge settings to make printable Hanzi grid paper, then preview and save the Chinese character grid as a PDF.": "可以选择田字格或米字格，预览后下载 PDF；也可直接从空白格纸入口下载。",
  "What does the Chinese worksheet generator create?": "生成器能制作什么？",
  "It creates editable Mandarin and Chinese writing worksheets with Hanzi, Pinyin, English meanings, tracing grids, blank writing cells, Hanzi grid paper, optional stroke-order guidance, and PDF output.": "可以制作带汉字、拼音、英文释义、描红、空白格和可选笔顺的字帖，并下载 PDF。",
  "Can I paste English words into the worksheet generator?": "可以粘贴英文词汇吗？",
  "Yes. Paste English or Chinese vocabulary, review the filled Hanzi and Pinyin, edit every row, and print the final worksheet.": "可以。粘贴后核对汉字和拼音，补填未匹配内容，再打印最终字帖。",
  "Does the worksheet generator include stroke order?": "生成器提供笔顺吗？",
  "Yes. You can show stroke-order guidance on worksheet rows and use the stroke-order tool to check a character before printing.": "可以在新字精学模式中显示笔顺，也可以先通过笔顺工具查询。",
  "Can I make Mandarin practice sheets and Hanzi grid paper?": "可以制作汉字练习纸和格纸吗？",
  "Yes. The generator works as a Mandarin worksheet generator and lets you print Tian Zi Ge or Mi Zi Ge Hanzi grid paper for Chinese character practice.": "可以制作汉字练习纸，选择田字格或米字格后下载打印。",
  "Chinese Stroke Order": "汉字笔顺查询", "Start continuous practice": "开始连续练习", "Browse character guides": "浏览汉字指南",
  "Learn the order rules": "学习笔顺规则", "Explore components": "查看汉字部件", "Type a character": "输入汉字", "Draw a character": "手写找字",
  "Chinese character": "汉字", "Show stroke order": "查看笔顺", "Selected character": "当前汉字", "Ready for stroke-order lookup": "可以查询笔顺",
  "Type a Hanzi or draw one you cannot identify, then watch its strokes, practise on screen, or add it to a worksheet.": "输入或手写一个汉字，查看笔顺、在屏幕上练习，或加入字帖。",
  "Play": "播放", "Next stroke": "下一笔", "Restart": "重新开始", "Practice": "练习", "Simplified": "简体", "Traditional": "繁体",
  "Add to worksheet": "加入字帖", "Stroke sequence": "笔画顺序", "Stroke-by-stroke": "逐笔示范", "Practise this character": "练习这个字", "Open worksheet": "打开字帖",
  "Stroke names differ between teaching systems. The animation shows where each stroke starts and how it moves.": "不同教学体系的笔画名称可能不同。动画展示每一笔的起点和运笔方向。",
  "Practice Chinese Characters": "汉字书写练习", "Continuous follow & fill": "连续跟写练习", "How this practice works": "怎样练习",
  "Stay close to each standard template stroke and move at your own pace. Complete one Hanzi, then continue through a recommended practice set.": "沿着示范笔画按自己的速度书写。完成一个字后，继续练习同组的汉字。",
  "Your cursor controls the speed and position of the reveal. The finished stroke keeps the clean template shape.": "鼠标或手指控制描写进度，完成的笔画保留标准字形。",
  "Practise any single Hanzi": "输入想练习的汉字", "Draw to find a character": "手写查找汉字", "Practise": "开始练习", "Previous": "上一个", "Random": "随机", "Next": "下一个",
  "Completed strokes move to the next character automatically.": "完成全部笔画后会自动进入下一个字。", "Follow & fill": "跟随描写", "Open character guide": "查看汉字指南", "Print practice sheet": "打印练习纸",
  "Choose a character practice set": "选择一组汉字练习", "Recommended next": "接下来可以练习", "Start set": "开始这组", "Browse all character guides": "浏览全部汉字指南",
  "Free Hanzi Grid Paper": "免费汉字格纸", "Printable Hanzi practice": "可打印汉字练习纸", "View printable page": "查看打印页面", "Download PDF": "下载 PDF", "Customise this grid": "自定义格纸",
  "Download printable Tian Zi Ge, Mi Zi Ge, and blank Chinese writing paper PDFs, or open a template in the worksheet maker to add your own characters and practice settings.": "下载田字格、米字格和空白练字纸 PDF，或打开生成器添加自己的汉字与练习设置。",
  "HSK vocabulary lists for Chinese writing practice": "用于书写练习的 HSK 词表", "Choose the right vocabulary path": "选择适合的词表", "Not sure which version?": "不确定选哪个版本？",
  "Check the level of your own text": "检测自己文章的词汇等级", "Start with your system and level": "选择版本和等级", "Thirteen curated lists": "13 份分级词表", "Browse and select words": "浏览并选词",
  "Compare HSK 2.0 and HSK 3.0, search each level by Hanzi, Pinyin, or English, and send exactly the words you choose to a printable worksheet.": "比较 HSK 2.0 和 3.0，按汉字、拼音或英文搜索各级词汇，将选中词条加入字帖。",
  "HSK Level Checker for Chinese Text": "中文文本 HSK 等级检测", "Turn a reading into a study list": "把阅读材料变成学习词表", "A study aid, not a score": "用于辅助学习，不代表考试成绩",
  "Paste a lesson, article excerpt, or message. Compare its HSK 2.0 and 3.0 vocabulary profile, isolate terms above your target, and send the difficult set into a printable writing worksheet.": "粘贴课文或文章，比较 HSK 2.0 与 3.0 的词汇等级，选出超过目标等级的词，制作练习字帖。",
  "The report classifies catalog matches. It does not predict an official exam score, comprehension, grammar control, or speaking ability.": "报告只对匹配到的词汇分级，不预测考试成绩、理解能力、语法或口语水平。",
  "Paste Chinese text": "粘贴中文文本", "Try a sample": "试用示例", "Beginner": "入门", "Daily life": "日常生活", "Formal": "正式表达",
  "HSK version": "HSK 版本", "My target level": "我的目标等级", "Analyze this text": "分析文本", "The analysis runs in your browser. The text is not uploaded or stored.": "分析在浏览器中完成，不上传或保存文本。",
  "Practise difficult items": "练习难词", "Hanzi occurrences": "个汉字", "unique matched terms": "个匹配词", "items above target or unclassified": "个超目标或未分类词",
  "Level distribution": "等级分布", "Browse HSK lists": "浏览 HSK 词表", "Create worksheet": "制作字帖", "Analyze": "分析", "Search": "搜索",
  "Select first 20": "选择前 20 个", "Clear selection": "清空选择", "Make worksheet": "制作字帖",
  "Chinese characters learners confuse—and how to choose": "易混汉字与区分方法", "Make the decision, not a guess": "掌握区分方法",
  "Choose by sentence role": "根据句子成分区分", "Grammar and usage": "语法与用法", "Map the relationship": "理解关系", "Direction and contrast": "方向与对比", "Watch the moving pen": "观察运笔", "Shape and recognition": "字形与辨认", "See rules and corrections": "查看规则与纠错",

  "Greetings": "问候语",
  "Days & Months": "星期与月份",
  "Food & Drinks": "食物与饮品",
  "Animals for Kids": "动物",
  "HSK 1 Writing Practice": "HSK 一级",
  "School & Classroom": "学校与教室",
  "Daily Routine": "日常生活",
  "Weather & Seasons": "天气与季节",
  "Body & Health": "身体与健康",
  "Home & Rooms": "家与房间",
  "Transportation": "交通工具",
  "Travel": "旅行中文",
  "Shopping": "购物中文",
  "Restaurant": "餐厅中文",
  "Hobbies & Sports": "爱好与运动",
  "Chinese New Year": "春节",
  "Jobs & Work": "工作与职业",
  "HSK 2 Writing Practice": "HSK 二级",
  "HSK 3 Writing Practice": "HSK 三级",
  "Basic Chinese Strokes": "基本笔画",
  "Chinese Radicals": "汉字部首",
  "Pinyin and Hanzi Practice": "拼音与汉字",
  "Stroke Order Practice": "笔顺练习",
  "Classical Poem Copying": "古诗抄写",
  "HSK 3 Campus Life": "HSK 3 校园生活",
  "HSK 3 Health": "HSK 3 健康",
  "HSK 3 Shopping & Money": "HSK 3 购物与钱",
  "HSK 3 Technology": "HSK 3 科技生活",
  "HSK 3 Exams & Grades": "HSK 3 考试与成绩",
  "HSK 3 Apartment & Home": "HSK 3 家与房间",
  "HSK 3 Office Teamwork": "HSK 3 办公与合作",
  "Top 100 Chinese Characters": "常用汉字 100",
  "Tian Zi Ge Beginner Worksheet": "田字格练习纸",
  "Chinese First Characters": "入门汉字",
  "HSK 4 Writing Practice": "HSK 四级",
  "HSK 5 Writing Practice": "HSK 五级",
  "Top 200 Chinese Characters": "常用汉字 200",
  "Mi Zi Ge Beginner Worksheet": "米字格练习纸",
  "Chinese Numbers 1-100": "中文数字 1-100",
  "Chinese Measure Words": "中文量词",
  "Common Chinese Verbs": "常用中文动词",
  "Home Practice": "家庭练习", "All ages": "所有年龄", "Teens & Adults": "青少年与成人",
};

export function translateUi(locale: string, value: string): string {
  if (!isChineseLocale(locale)) return value;
  const normalized = value.trim().replace(/\s+/g, " ");
  if (/^Ages? [\d–+ -]+$/.test(normalized)) return normalized.replace(/^Ages? /, "年龄 ");
  return chinese[normalized] ?? value;
}
